import {
  World,
  Mission,
  Lesson,
  Activity,
  PracticeQuestion,
  Badge,
  Reflection,
  Reference,
  TournamentPackage,
  TournamentQuestion,
  TournamentEvent,
  TournamentParticipant,
  TournamentResult,
  User,
  School,
  Class,
  ClassMember,
  StudentProgress,
  ImportAuditLog,
  WorkflowReviewLog,
  ContentVersionEntry,
} from '../types';

export const seedWorlds: World[] = [
  {
    id: 'cinta',
    code: 'cinta',
    title: 'Cinta Rupiah',
    tagline: 'Mengenali keaslian, merawat fisik, dan menjaga Rupiah dengan rasa cinta.',
    themeColor: 'red',
    icon: 'heart',
    orderIndex: 1,
    description: 'Tunjukkan rasa cinta kepada Rupiah dengan mengenali keasliannya dan merawatnya melalui prinsip 5J agar uang kita selalu bersih, utuh, dan layak edar!',
    status: 'published',
  },
  {
    id: 'bangga',
    code: 'bangga',
    title: 'Bangga Rupiah',
    tagline: 'Bangga menggunakan Rupiah sebagai simbol kedaulatan dan pemersatu bangsa.',
    themeColor: 'blue',
    icon: 'flag',
    orderIndex: 2,
    description: 'Rupiah bukan sekadar alat bayar, tapi merupakan simbol kedaulatan negara Republik Indonesia dan pemersatu bangsa dari Sabang sampai Merauke.',
    status: 'published',
  },
  {
    id: 'paham',
    code: 'paham',
    title: 'Paham Rupiah',
    tagline: 'Paham cara bertransaksi, berbelanja bijak, dan rajin berhemat sejak dini.',
    themeColor: 'orange',
    icon: 'lightbulb',
    orderIndex: 3,
    description: 'Jadilah generasi cerdas finansial yang paham membedakan antara kebutuhan vs keinginan, bijak bertransaksi, serta rajin menabung untuk masa depan.',
    status: 'published',
  },
];

export const seedMissions: Mission[] = [
  // 3 Misi Cinta
  {
    id: 'JR-C01',
    worldId: 'cinta',
    code: 'JR-C01',
    title: 'Mengenal Rupiah & Sejarahnya',
    subtitle: 'Dari Sistem Barter hingga Uang Kertas & Logam TE 2022',
    levelNumber: 1,
    summary: 'Mengenal sejarah terciptanya uang dari masa barter, penerbitan ORI 1946, serta ragam pecahan uang Rupiah kertas dan logam.',
    bigQuestion: 'Bagaimana asal mula manusia menciptakan uang dan mengapa Rupiah menjadi alat pembayaran yang sah di Indonesia?',
    openingStory: 'Sebelum uang diciptakan, manusia bertukar barang secara langsung (barter). Rupi mengajak kita menjelajahi perjalanan sejarah uang hingga terbitnya Rupiah sebagai identitas bangsa.',
    learningPoints: [
      'Memahami sistem barter dan asal-usul terciptanya uang',
      'Mengenal ragam pecahan uang Rupiah kertas dan logam TE 2022',
      'Sejarah perjalanan Rupiah sebagai alat transaksi resmi',
    ],
    questionDisplayCount: 5,
    status: 'published',
    xpReward: 150,
    pointReward: 150,
    orderIndex: 1,
    badgeId: 'BDG-01',
    iconName: 'book-open',
  },
  {
    id: 'JR-C02',
    worldId: 'cinta',
    code: 'JR-C02',
    title: 'Ciri Keaslian Uang Rupiah',
    subtitle: 'Metode 3D: Dilihat, Diraba, Diterawang',
    levelNumber: 2,
    summary: 'Mempelajari cara mengidentifikasi keaslian uang Rupiah kertas dan logam melalui unsur pengaman modern 3D.',
    bigQuestion: 'Bagaimana cara kita membuktikan keaslian selembar uang Rupiah dengan panca indera kita sendiri?',
    openingStory: 'Budi dan Rupi sedang berada di pasar tradisional. Ketika menerima uang kembalian baru, Rupi mengajak Budi mempraktikkan metode 3D agar yakin uang tersebut asli dan aman digunakan.',
    learningPoints: [
      'Memahami teknik 3D (Dilihat, Diraba, Diterawang)',
      'Mengenal benang pengaman, color shifting, dan gambar tersembunyi',
      'Membedakan uang rupiah asli dari uang palsu',
    ],
    questionDisplayCount: 5,
    status: 'published',
    xpReward: 200,
    pointReward: 200,
    orderIndex: 2,
    badgeId: 'BDG-02',
    iconName: 'sparkles',
  },
  {
    id: 'JR-C03',
    worldId: 'cinta',
    code: 'JR-C03',
    title: 'Merawat Rupiah (Prinsip 5J)',
    subtitle: 'Prinsip 5J: Menjaga Fisik Uang & Kelayakan Edar',
    levelNumber: 3,
    summary: 'Menerapkan 5 larangan merusak uang Rupiah (5J) serta mengenal kriteria Uang Layak Edar (ULE) dan Uang Tidak Layak Edar (UTLE).',
    bigQuestion: 'Mengapa merawat fisik uang Rupiah sama dengan menghormati pahlawan dan simbol negara kita?',
    openingStory: 'Di kantin sekolah, Siti melihat uang yang lusuh dan terlipat. Siti bersama Rupi bertekad mengedukasi teman-temannya tentang gerakan 5J agar uang Rupiah selalu bersih, awet, dan layak edar.',
    learningPoints: [
      'Menguasai 5 Prinsip Merawat Rupiah (5J)',
      'Membedakan Uang Layak Edar (ULE) dan Uang Tidak Layak Edar (UTLE)',
      'Praktik menyimpan uang secara rapi dalam dompet panjang tanpa dilipat',
    ],
    questionDisplayCount: 5,
    status: 'published',
    xpReward: 250,
    pointReward: 250,
    orderIndex: 3,
    badgeId: 'BDG-03',
    iconName: 'shield-check',
  },

  // 3 Misi Bangga
  {
    id: 'JR-B04',
    worldId: 'bangga',
    code: 'JR-B04',
    title: 'Rupiah dan Indonesiaku',
    subtitle: 'Rupiah Simbol Kedaulatan NKRI',
    levelNumber: 4,
    summary: 'Menghayati makna Rupiah sebagai lambang kemerdekaan dan kedaulatan hukum Negara Kesatuan Republik Indonesia.',
    bigQuestion: 'Mengapa mata uang Rupiah disebut sebagai salah satu pilar kedaulatan bangsa Indonesia yang setara dengan bendera dan lagu kebangsaan?',
    openingStory: 'Dalam kelas sejarah, Bu Guru menceritakan perjuangan para pendiri bangsa menerbitkan Oeang Republik Indonesia (ORI) tahun 1946 untuk membuktikan kedaulatan bangsa yang baru merdeka.',
    learningPoints: [
      'Makna Lambang Garuda dan Frasa NKRI pada uang Rupiah',
      'Sejarah Oeang Republik Indonesia (ORI) tahun 1946',
      'Pentingnya menjaga kehormatan simbol negara',
    ],
    questionDisplayCount: 5,
    status: 'published',
    xpReward: 180,
    pointReward: 180,
    orderIndex: 4,
    badgeId: 'BDG-04',
    iconName: 'shield',
  },
  {
    id: 'JR-B05',
    worldId: 'bangga',
    code: 'JR-B05',
    title: 'Aku Bangga Menggunakan Rupiah',
    subtitle: 'Satu-satunya Alat Pembayaran Sah di NKRI',
    levelNumber: 5,
    summary: 'Memahami UU No. 7 Tahun 2011 tentang Mata Uang dan kewajiban bertransaksi dengan Rupiah di seluruh pelosok Indonesia.',
    bigQuestion: 'Mengapa di seluruh pelosok bumi pertiwi dari Sabang sampai Merauke kita wajib menggunakan Rupiah saat bertransaksi?',
    openingStory: 'Saat berwisata ke Pulau Weh di ujung barat Indonesia, Edo melihat sebuah toko cenderamata. Edo bangga membayar seluruh belanjaannya dengan Rupiah sebagai bentuk cinta tanah air.',
    learningPoints: [
      'Kewajiban hukum menggunakan Rupiah di seluruh wilayah Indonesia',
      'Perlindungan stabilitas nilai tukar Rupiah',
      'Menolak penggunaan mata uang asing untuk transaksi domestik',
    ],
    questionDisplayCount: 5,
    status: 'published',
    xpReward: 220,
    pointReward: 220,
    orderIndex: 5,
    badgeId: 'BDG-05',
    iconName: 'coins',
  },
  {
    id: 'JR-B06',
    worldId: 'bangga',
    code: 'JR-B06',
    title: 'Rupiah Menyatukan Kita',
    subtitle: 'Jelajah Pahlawan & Budaya Nusantara',
    levelNumber: 6,
    summary: 'Mengenal pahlawan nasional, tarian tradisional, dan keindahan alam nusantara yang tercantum pada setiap pecahan uang Rupiah.',
    bigQuestion: 'Bagaimana selembar uang Rupiah dapat merangkum ribuan pulau, pahlawan kemerdekaan, dan tari-tarian nusantara?',
    openingStory: 'Sari dan Dimas membuka album koleksi uang Rupiah TE 2022. Mereka terpukau melihat deretan pahlawan dari berbagai penjuru nusantara dan keindahan tarian daerah yang terukir indah.',
    learningPoints: [
      'Mengenal profil pahlawan nasional pada pecahan Rupiah TE 2022',
      'Menjelajahi ragam tarian dan lanskap alam Indonesia pada uang kertas',
      'Rupiah sebagai jembatan perekat persatuan lintas pulau',
    ],
    questionDisplayCount: 5,
    status: 'published',
    xpReward: 280,
    pointReward: 280,
    orderIndex: 6,
    badgeId: 'BDG-06',
    iconName: 'users',
  },

  // 3 Misi Paham
  {
    id: 'JR-P07',
    worldId: 'paham',
    code: 'JR-P07',
    title: 'Petualangan Transaksi',
    subtitle: 'Cerdas Hitung & Pembayaran Non-Tunai QRIS',
    levelNumber: 7,
    summary: 'Belajar menghitung uang dengan teliti, memeriksa kembalian, dan mengenal kemudahan transaksi digital aman seperti QRIS.',
    bigQuestion: 'Bagaimana cara kita bertransaksi dengan cepat, aman, dan teliti baik secara tunai maupun digital?',
    openingStory: 'Di koperasi sekolah yang ramai, Rupi memandu para siswa menghitung belanjaan buku tulis dan mempraktikkan pembayaran non-tunai yang cepat dan aman dengan QRIS.',
    learningPoints: [
      'Keterampilan berhitung uang saku dan mengecek kembalian',
      'Mengenal transaksi non-tunai CeMUAMAH (Cepat, Mudah, Murah, Aman, Handal)',
      'Keamanan bertransaksi digital bagi pelajar',
    ],
    questionDisplayCount: 5,
    status: 'published',
    xpReward: 150,
    pointReward: 150,
    orderIndex: 7,
    badgeId: 'BDG-07',
    iconName: 'receipt',
  },
  {
    id: 'JR-P08',
    worldId: 'paham',
    code: 'JR-P08',
    title: 'Belanja dengan Bijak',
    subtitle: 'Memilah Kebutuhan vs Keinginan',
    levelNumber: 8,
    summary: 'Mengembangkan kebiasaan belanja yang rasional dengan memprioritaskan kebutuhan sekolah sebelum menuruti keinginan sesaat.',
    bigQuestion: 'Bagaimana cara menentukan apakah suatu barang benar-benar kita butuhkan atau hanya keinginan sesaat?',
    openingStory: 'Menjelang tahun ajaran baru, Doni diajak ibunya ke toko perlengkapan. Doni belajar menyusun daftar belanja prioritas agar uang tabungannya tidak habis sia-sia.',
    learningPoints: [
      'Membedakan kebutuhan pokok vs keinginan',
      'Membuat daftar belanja sederhana dan membandingkan harga',
      'Mencegah perilaku konsumtif sejak usia dini',
    ],
    questionDisplayCount: 5,
    status: 'published',
    xpReward: 200,
    pointReward: 200,
    orderIndex: 8,
    badgeId: 'BDG-08',
    iconName: 'shopping-cart',
  },
  {
    id: 'JR-P09',
    worldId: 'paham',
    code: 'JR-P09',
    title: 'Tabungan Masa Depanku',
    subtitle: 'Disiplin Menabung & Simpanan Pelajar (SimPel)',
    levelNumber: 9,
    summary: 'Membangun disiplin menabung di celengan dan rekening tabungan Simpanan Pelajar (SimPel) di bank.',
    bigQuestion: 'Mengapa menyisihkan sedikit uang setiap hari dapat membawa kita meraih cita-cita besar di masa depan?',
    openingStory: 'Nina bermimpi memiliki set peralatan melukis profesional. Dengan bimbingan Rupi, Nina mulai menyisihkan uang sakunya setiap hari dan membuka rekening SimPel pertamanya di bank.',
    learningPoints: [
      'Manfaat menabung secara rutin setiap hari atau minggu',
      'Mengenal produk tabungan Simpanan Pelajar (SimPel)',
      'Menetapkan target impian jangka pendek dan jangka panjang',
    ],
    questionDisplayCount: 5,
    status: 'published',
    xpReward: 300,
    pointReward: 300,
    orderIndex: 9,
    badgeId: 'BDG-09',
    iconName: 'piggy-bank',
  },
];

export const seedLessons: Lesson[] = [
  // Misi 1 (3 Lessons) - JR-C01
  {
    id: 'MAT-001',
    missionId: 'JR-C01',
    code: 'MAT-001',
    title: 'Dari Barter ke Uang',
    summary: 'Sejarah terciptanya uang dari masa barter hingga menjadi alat tukar resmi.',
    studentText: 'Dahulu kala sebelum uang diciptakan, manusia bertukar barang secara langsung yang disebut sistem Barter. Misalnya, menukar sekarung beras dengan seekor ayam. Namun, barter sangat sulit karena kedua pihak harus sama-sama membutuhkan barang tersebut pada waktu yang sama. Oleh karena itu, manusia menciptakan Uang sebagai alat tukar resmi yang praktis, diterima semua orang, dan memiliki nilai pasti.',
    content: 'Dahulu kala sebelum uang diciptakan, manusia bertukar barang secara langsung yang disebut sistem Barter. Misalnya, menukar sekarung beras dengan seekor ayam. Namun, barter sangat sulit karena kedua pihak harus sama-sama membutuhkan barang tersebut pada waktu yang sama. Oleh karena itu, manusia menciptakan Uang sebagai alat tukar resmi yang praktis, diterima semua orang, dan memiliki nilai pasti.',
    keyTakeaways: ['Barter adalah sistem tukar-menukar barang secara langsung', 'Uang diciptakan sebagai alat tukar resmi yang praktis dan bernilai pasti'],
    imageUrl: '',
    imageBrief: 'Ilustrasi komik edukatif masa barter bertukar beras dan garam beralih ke uang koin dan uang kertas Rupiah',
    imageCaption: 'Dari masa barter menuju alat pembayaran uang Rupiah resmi',
    interactionPrompt: 'Bayangkan jika kamu ingin membeli buku cerita tetapi hanya punya mangga, apa kesulitan yang kamu hadapi jika masih memakai sistem barter?',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 3,
    contentOrder: 1,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'MAT-002',
    missionId: 'JR-C01',
    code: 'MAT-002',
    title: 'Kenalan dengan Rupiah',
    summary: 'Mengenal uang resmi Negara Kesatuan Republik Indonesia dari pecahan kertas hingga logam.',
    studentText: 'Rupiah adalah mata uang resmi Negara Kesatuan Republik Indonesia. Uang Rupiah diterbitkan dan diedarkan oleh Bank Indonesia. Rupiah terdiri dari dua jenis: Uang Kertas dan Uang Logam. Setiap pecahan uang Rupiah memiliki desain unik yang menampilkan pahlawan nasional, keindahan tarian tradisional, serta kekayaan alam Nusantara.',
    content: 'Rupiah adalah mata uang resmi Negara Kesatuan Republik Indonesia. Uang Rupiah diterbitkan dan diedarkan oleh Bank Indonesia. Rupiah terdiri dari dua jenis: Uang Kertas dan Uang Logam. Setiap pecahan uang Rupiah memiliki desain unik yang menampilkan pahlawan nasional, keindahan tarian tradisional, serta kekayaan alam Nusantara.',
    keyTakeaways: ['Rupiah adalah mata uang tunggal yang sah di seluruh wilayah NKRI', 'Diterbitkan dalam bentuk uang kertas dan uang logam oleh Bank Indonesia'],
    imageUrl: '',
    imageBrief: 'Infografis deretan pecahan uang Rupiah kertas dan logam Tahun Emisi 2022 dari Rp1.000 hingga Rp100.000',
    imageCaption: 'Pecahan uang kertas dan logam Rupiah TE 2022',
    interactionPrompt: 'Coba sebutkan pecahan uang kertas dan uang logam Rupiah yang sering kamu gunakan sehari-hari!',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 4,
    contentOrder: 2,
    orderIndex: 2,
    status: 'published',
  },
  {
    id: 'MAT-003',
    missionId: 'JR-C01',
    code: 'MAT-003',
    title: 'Rupiah Punya Cerita',
    summary: 'Kisah sejarah perjuangan bangsa dan nilai kedaulatan di setiap lembaran Rupiah.',
    studentText: 'Tahukah kamu? Setiap lembar Rupiah menyimpan cerita sejarah perjuangan dan identitas bangsa kita. Sejak diterbitkannya Oeang Republik Indonesia (ORI) pada tanggal 30 Oktober 1946, Rupiah menjadi simbol kedaulatan dan pemersatu bangsa dari Sabang sampai Merauke. Mengenal Rupiah berarti mengenal kekayaan dan sejarah Indonesia.',
    content: 'Tahukah kamu? Setiap lembar Rupiah menyimpan cerita sejarah perjuangan dan identitas bangsa kita. Sejak diterbitkannya Oeang Republik Indonesia (ORI) pada tanggal 30 Oktober 1946, Rupiah menjadi simbol kedaulatan dan pemersatu bangsa dari Sabang sampai Merauke. Mengenal Rupiah berarti mengenal kekayaan dan sejarah Indonesia.',
    keyTakeaways: ['Rupiah merekam jejak sejarah perjuangan kemerdekaan bangsa Indonesia', 'Setiap lembar uang merekatkan persatuan seluruh pelosok tanah air'],
    imageUrl: '',
    imageBrief: 'Visual kilas balik sejarah penerbitan ORI 1946 berdampingan dengan uang Rupiah modern TE 2022 dan peta Indonesia',
    imageCaption: 'Kilas balik sejarah ORI 1946 hingga Rupiah TE 2022',
    interactionPrompt: 'Mengapa kita harus bangga menggunakan uang Rupiah dibandingkan mata uang negara lain?',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 3,
    contentOrder: 3,
    orderIndex: 3,
    status: 'published',
  },

  // Misi 2 (2 Lessons) - JR-C02
  {
    id: 'MAT-004',
    missionId: 'JR-C02',
    code: 'MAT-004',
    title: 'Rupiah Juga Perlu Dirawat',
    summary: 'Rupiah digunakan banyak orang setiap hari sehingga kualitas fisiknya perlu dijaga agar tetap nyaman digunakan.',
    studentText: 'Rupiah digunakan banyak orang setiap hari. Ada uang yang masih rapi dan mudah digunakan, ada yang sudah lusuh, dan ada pula yang rusak karena robek, berlubang, terbakar, atau terkena perlakuan yang tidak baik. Bank Indonesia juga memilah uang yang tidak layak edar agar kualitas uang yang beredar tetap terjaga. Kita membantu dengan merawat Rupiah agar tetap nyaman digunakan dan mudah dikenali.',
    content: 'Rupiah digunakan banyak orang setiap hari. Ada uang yang masih rapi dan mudah digunakan, ada yang sudah lusuh, dan ada pula yang rusak karena robek, berlubang, terbakar, atau terkena perlakuan yang tidak baik. Bank Indonesia juga memilah uang yang tidak layak edar agar kualitas uang yang beredar tetap terjaga. Kita membantu dengan merawat Rupiah agar tetap nyaman digunakan dan mudah dikenali.',
    keyTakeaways: ['Rupiah yang terawat nyaman digunakan dan mudah dikenali', 'BI memilah uang tidak layak edar untuk menjaga kualitas uang'],
    imageUrl: '',
    imageBrief: 'Ilustrasi perbandingan uang bersih terawat vs uang lusuh dan uang rusak',
    imageCaption: 'Kondisi uang Rupiah dalam peredaran',
    interactionPrompt: 'Mana yang terlihat paling terawat? Apa alasannya?',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 3,
    contentOrder: 1,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'MAT-005',
    missionId: 'JR-C02',
    code: 'MAT-005',
    title: 'Ingat 5J!',
    summary: 'Prinsip 5J: Jangan dilipat, Jangan dicoret, Jangan diremas, Jangan distapler, dan Jangan dibasahi.',
    studentText: 'Cara sederhana merawat uang kertas dapat diingat dengan 5J: Jangan dilipat, Jangan dicoret, Jangan diremas, Jangan distapler, dan Jangan dibasahi. Simpan Rupiah dengan rapi agar kita ikut menjaga kualitas uang yang beredar.',
    content: 'Cara sederhana merawat uang kertas dapat diingat dengan 5J: Jangan dilipat, Jangan dicoret, Jangan diremas, Jangan distapler, dan Jangan dibasahi. Simpan Rupiah dengan rapi agar kita ikut menjaga kualitas uang yang beredar.',
    keyTakeaways: ['Ingat prinsip 5J untuk uang kertas', 'Simpan Rupiah dengan rapi di dompet tanpa dilipat'],
    imageUrl: '',
    imageBrief: 'Infografis 5J: Jangan dilipat, dicoret, diremas, distapler, dibasahi',
    imageCaption: 'Panduan prinsip 5J merawat Rupiah',
    interactionPrompt: 'Pilih tindakan yang sesuai dengan 5J.',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 3,
    contentOrder: 2,
    orderIndex: 2,
    status: 'published',
  },

  // Misi 3 (3 Lessons) - JR-C03
  {
    id: 'MAT-006',
    missionId: 'JR-C03',
    code: 'MAT-006',
    title: 'Kriteria Uang Layak Edar (ULE)',
    summary: 'Standar kualitas fisik uang Rupiah yang nyaman digunakan masyarakat.',
    studentText: 'Uang Layak Edar (ULE) adalah uang Rupiah asli yang memenuhi standar kualitas Bank Indonesia untuk digunakan masyarakat bertransaksi secara nyaman. Ciri ULE adalah uang bersih, tidak kusam, gambar dan angka nominal terbaca sangat jelas, serta tidak ada sobekan atau tambalan selotip.',
    content: 'Uang Layak Edar (ULE) adalah uang Rupiah asli yang memenuhi standar kualitas Bank Indonesia untuk digunakan masyarakat bertransaksi secara nyaman. Ciri ULE adalah uang bersih, tidak kusam, gambar dan angka nominal terbaca sangat jelas, serta tidak ada sobekan atau tambalan selotip.',
    keyTakeaways: ['ULE memastikan transaksi berjalan lancar dan nyaman', 'Masyarakat berhak mendapatkan uang berkualitas baik'],
    imageUrl: '',
    imageBrief: 'Foto komparasi Uang Layak Edar (bersih mengkilap) berdampingan dengan standar edar Bank Indonesia',
    imageCaption: 'Perbandingan ULE dan UTLE',
    interactionPrompt: 'Mengapa transaksi jual beli terasa lebih menyenangkan dan cepat jika menggunakan Uang Layak Edar?',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 3,
    contentOrder: 1,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'MAT-007',
    missionId: 'JR-C03',
    code: 'MAT-007',
    title: 'Mengenal Uang Tidak Layak Edar (UTLE)',
    summary: 'Kategori uang lusuh, uang cacat, dan uang rusak.',
    studentText: 'Uang Tidak Layak Edar (UTLE) terdiri dari tiga kategori: 1. Uang Lusuh (kotor, bau, atau kusam), 2. Uang Cacat (hasil cetakan yang tidak sempurna dari pabrik), dan 3. Uang Rusak (uang terbakar, sobek, atau berlubang). Uang UTLE tidak boleh diedarkan kembali dan harus diserahkan ke bank untuk diganti.',
    content: 'Uang Tidak Layak Edar (UTLE) terdiri dari tiga kategori: 1. Uang Lusuh (kotor, bau, atau kusam), 2. Uang Cacat (hasil cetakan yang tidak sempurna dari pabrik), dan 3. Uang Rusak (uang terbakar, sobek, atau berlubang). Uang UTLE tidak boleh diedarkan kembali dan harus diserahkan ke bank untuk diganti.',
    keyTakeaways: ['Uang lusuh ditarik untuk dimusnahkan secara resmi', 'Uang rusak dapat ditukar sesuai ketentuan'],
    imageUrl: '',
    imageBrief: 'Tiga kotak perbandingan: Uang Lusuh, Uang Cacat, dan Uang Rusak dengan penjelasan visual',
    imageCaption: 'Kategori Uang Tidak Layak Edar',
    interactionPrompt: 'Jika kamu menerima uang kembalian yang sobek sebagian, apa yang sebaiknya kamu lakukan?',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 3,
    contentOrder: 2,
    orderIndex: 2,
    status: 'published',
  },
  {
    id: 'MAT-008',
    missionId: 'JR-C03',
    code: 'MAT-008',
    title: 'Prosedur Penukaran Uang di Bank Indonesia (Aplikasi PINTAR)',
    summary: 'Kemudahan menukar uang rusak atau pecahan baru melalui layanan resmi.',
    studentText: 'Bank Indonesia menyediakan layanan penukaran uang rusak dan uang lusuh tanpa dipungut biaya sepeser pun. Masyarakat dapat menggunakan aplikasi website PINTAR (pintar.bi.go.id) untuk memilih jadwal dan lokasi kas keliling Bank Indonesia terdekat secara mudah, tertib, dan pasti.',
    content: 'Bank Indonesia menyediakan layanan penukaran uang rusak dan uang lusuh tanpa dipungut biaya sepeser pun. Masyarakat dapat menggunakan aplikasi website PINTAR (pintar.bi.go.id) untuk memilih jadwal dan lokasi kas keliling Bank Indonesia terdekat secara mudah, tertib, dan pasti.',
    keyTakeaways: ['Penukaran uang di BI tidak dipungut biaya', 'Gunakan aplikasi PINTAR untuk kepastian jadwal'],
    imageUrl: '',
    imageBrief: 'Ilustrasi mobil Kas Keliling Bank Indonesia melayani penukaran uang masyarakat dan tampilan layar PINTAR',
    imageCaption: 'Layanan Kas Keliling Bank Indonesia',
    interactionPrompt: 'Kunjungi portal pintar.bi.go.id bersama bimbingan guru/orang tua untuk melihat jadwal kas keliling terdekat!',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 4,
    contentOrder: 3,
    orderIndex: 3,
    status: 'published',
  },

  // Misi 4 (3 Lessons) - JR-B04
  {
    id: 'MAT-010',
    missionId: 'JR-B04',
    code: 'MAT-010',
    title: 'Rupiah sebagai Simbol Kedaulatan Negara',
    summary: 'Rupiah sejajar dengan Bendera Merah Putih, Bahasa Indonesia, dan Lagu Indonesia Raya.',
    studentText: 'Rupiah berkedudukan setara dengan simbol kedaulatan negara lainnya, yaitu Bendera Merah Putih, Bahasa Indonesia, dan Lagu Kebangsaan Indonesia Raya. Setiap lembar uang memuat lambang Garuda Pancasila dan frasa "Negara Kesatuan Republik Indonesia", menandakan kedaulatan hukum dan ekonomi kita.',
    content: 'Rupiah berkedudukan setara dengan simbol kedaulatan negara lainnya, yaitu Bendera Merah Putih, Bahasa Indonesia, dan Lagu Kebangsaan Indonesia Raya. Setiap lembar uang memuat lambang Garuda Pancasila dan frasa "Negara Kesatuan Republik Indonesia", menandakan kedaulatan hukum dan ekonomi kita.',
    keyTakeaways: ['Rupiah adalah atribut kedaulatan NKRI', 'Lambang Garuda dan tanda tangan resmi menegaskan keabsahannya'],
    imageUrl: '',
    imageBrief: 'Poster edukasi menampilkan 4 Simbol Kedaulatan Bangsa: Bendera, Bahasa, Lagu, dan Rupiah',
    imageCaption: 'Detail Lambang Negara Garuda pada Rupiah',
    interactionPrompt: 'Temukan letak Lambang Garuda Pancasila pada uang kertas Rupiah yang kamu miliki!',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 4,
    contentOrder: 1,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'MAT-011',
    missionId: 'JR-B04',
    code: 'MAT-011',
    title: 'Sejarah ORI (Oeang Republik Indonesia) 1946',
    summary: 'Perjuangan para pendiri bangsa menerbitkan mata uang sendiri pasca proklamasi.',
    studentText: 'Pada 30 Oktober 1946, pemerintah Indonesia menerbitkan mata uang pertama yaitu Oeang Republik Indonesia (ORI). Wakil Presiden Mohammad Hatta berpidato bahwa ORI adalah lambang kemerdekaan sejati, memutus ketergantungan pada mata uang penjajah Belanda dan Jepang. Tanggal ini kini diperingati sebagai Hari Oeang Republik Indonesia (HORI).',
    content: 'Pada 30 Oktober 1946, pemerintah Indonesia menerbitkan mata uang pertama yaitu Oeang Republik Indonesia (ORI). Wakil Presiden Mohammad Hatta berpidato bahwa ORI adalah lambang kemerdekaan sejati, memutus ketergantungan pada mata uang penjajah Belanda dan Jepang. Tanggal ini kini diperingati sebagai Hari Oeang Republik Indonesia (HORI).',
    keyTakeaways: ['30 Oktober diperingati sebagai Hari Oeang Republik Indonesia (HORI)', 'ORI menjadi bukti kemandirian bangsa'],
    imageUrl: '',
    imageBrief: 'Ilustrasi arsip bersejarah penerbitan lembaran ORI pertama 1946 dengan kutipan Bung Hatta',
    imageCaption: 'Lembaran ORI Emisi Pertama 1946',
    interactionPrompt: 'Bagaimana perasaanmu mengetahui para pejuang bangsa mencetak uang sendiri di tengah perang kemerdekaan?',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 4,
    contentOrder: 2,
    orderIndex: 2,
    status: 'published',
  },
  {
    id: 'MAT-012',
    missionId: 'JR-B04',
    code: 'MAT-012',
    title: 'Kedaulatan Rupiah di Wilayah 3T',
    summary: 'Menegakkan kedaulatan Rupiah hingga ke batas terluar nusantara.',
    studentText: 'Untuk menjaga kedaulatan wilayah perbatasan, Bank Indonesia bekerjasama dengan TNI Angkatan Laut menggelar Ekspedisi Kas Keliling ke pulau-pulau Terdepan, Terluar, dan Tertinggal (3T). Program ini memastikan saudara-saudara kita di pulau terluar selalu menggunakan Rupiah, bukan mata uang asing.',
    content: 'Untuk menjaga kedaulatan wilayah perbatasan, Bank Indonesia bekerjasama dengan TNI Angkatan Laut menggelar Ekspedisi Kas Keliling ke pulau-pulau Terdepan, Terluar, dan Tertinggal (3T). Program ini memastikan saudara-saudara kita di pulau terluar selalu menggunakan Rupiah, bukan mata uang asing.',
    keyTakeaways: ['Ekspedisi kas keliling 3T memperkuat kedaulatan perbatasan', 'Rupiah hadir di seluruh titik nusantara'],
    imageUrl: '',
    imageBrief: 'Kapal perang TNI-AL membawa tim Kas Keliling Bank Indonesia mendarat di pulau terluar Nusantara',
    imageCaption: 'Ekspedisi Kas Keliling Kepulauan 3T',
    interactionPrompt: 'Mengapa penting bagi warga di perbatasan pulau terluar untuk selalu menggunakan mata uang Rupiah?',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 3,
    contentOrder: 3,
    orderIndex: 3,
    status: 'published',
  },

  // Misi 5 (2 Lessons) - JR-B05
  {
    id: 'MAT-013',
    missionId: 'JR-B05',
    code: 'MAT-013',
    title: 'Undang-Undang Mata Uang No. 7 Tahun 2011',
    summary: 'Landasan hukum kewajiban penggunaan Rupiah di Indonesia.',
    studentText: 'Undang-Undang No. 7 Tahun 2011 mewajibkan seluruh transaksi pembayaran dan kewajiban keuangan di wilayah hukum Republik Indonesia diselesaikan menggunakan Rupiah. Menolak pembayaran dengan Rupiah yang sah merupakan tindakan melanggar hukum dan dapat dikenai sanksi pidana.',
    content: 'Undang-Undang No. 7 Tahun 2011 mewajibkan seluruh transaksi pembayaran dan kewajiban keuangan di wilayah hukum Republik Indonesia diselesaikan menggunakan Rupiah. Menolak pembayaran dengan Rupiah yang sah merupakan tindakan melanggar hukum dan dapat dikenai sanksi pidana.',
    keyTakeaways: ['Wajib bertransaksi dengan Rupiah di Indonesia', 'Penolakan terhadap Rupiah yang sah dapat dikenai sanksi hukum'],
    imageUrl: '',
    imageBrief: 'Grafis buku UU No. 7 Tahun 2011 dengan simbol kepastian hukum dan transaksi berdaulat Rupiah',
    imageCaption: 'UU No. 7 Tahun 2011 tentang Mata Uang',
    interactionPrompt: 'Apakah wisatawan asing yang berlibur di Bali boleh berbelanja di pasar lokal memakai Dollar? Jelaskan alasannya!',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 3,
    contentOrder: 1,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'MAT-014',
    missionId: 'JR-B05',
    code: 'MAT-014',
    title: 'Peran Rupiah dalam Menjaga Stabilitas Nilai Tukar',
    summary: 'Mengapa menggunakan Rupiah memperkuat perekonomian nasional.',
    studentText: 'Ketika kita mencintai dan selalu menggunakan Rupiah, permintaan terhadap mata uang kita akan tetap kuat. Hal ini membantu Bank Indonesia menjaga stabilitas nilai tukar Rupiah terhadap mata uang dunia, mengendalikan inflasi harga barang, dan menjaga perekonomian nasional tetap tangguh.',
    content: 'Ketika kita mencintai dan selalu menggunakan Rupiah, permintaan terhadap mata uang kita akan tetap kuat. Hal ini membantu Bank Indonesia menjaga stabilitas nilai tukar Rupiah terhadap mata uang dunia, mengendalikan inflasi harga barang, dan menjaga perekonomian nasional tetap tangguh.',
    keyTakeaways: ['Gunakan Rupiah untuk menjaga ketahanan ekonomi nasional', 'Cinta Rupiah berarti mendukung kemajuan bangsa'],
    imageUrl: '',
    imageBrief: 'Diagram alur bagaimana transaksi Rupiah menopang pertumbuhan ekonomi dan stabilitas harga barang kebutuhan',
    imageCaption: 'Perekonomian nasional yang mandiri dan kuat',
    interactionPrompt: 'Sebutkan satu tindakan sederhana yang bisa kamu lakukan untuk mendukung kekuatan nilai Rupiah!',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 3,
    contentOrder: 2,
    orderIndex: 2,
    status: 'published',
  },

  // Misi 6 (3 Lessons) - JR-B06
  {
    id: 'MAT-015',
    missionId: 'JR-B06',
    code: 'MAT-015',
    title: 'Pahlawan Nasional pada Uang Rupiah',
    summary: 'Mengenang jasa pahlawan yang terukir di setiap pecahan Rupiah.',
    studentText: 'Uang Rupiah TE 2022 mengabadikan figur 8 pahlawan nasional dari berbagai penjuru tanah air: Ir. Soekarno & Drs. Moh. Hatta (Rp100.000), Ir. H. Djuanda (Rp50.000), Dr. G.S.S.J. Ratulangi (Rp20.000), Frans Kaisiepo (Rp10.000), Dr. K.H. Idham Chalid (Rp5.000), Mohammad Hoesni Thamrin (Rp2.000), dan Tjut Meutia (Rp1.000).',
    content: 'Uang Rupiah TE 2022 mengabadikan figur 8 pahlawan nasional dari berbagai penjuru tanah air: Ir. Soekarno & Drs. Moh. Hatta (Rp100.000), Ir. H. Djuanda (Rp50.000), Dr. G.S.S.J. Ratulangi (Rp20.000), Frans Kaisiepo (Rp10.000), Dr. K.H. Idham Chalid (Rp5.000), Mohammad Hoesni Thamrin (Rp2.000), dan Tjut Meutia (Rp1.000).',
    keyTakeaways: ['Pahlawan mencerminkan keberagaman Nusantara', 'Menumbuhkan rasa hormat dan keteladanan bagi generasi muda'],
    imageUrl: '',
    imageBrief: 'Galeri potret pahlawan nasional pada uang Rupiah TE 2022 beserta daerah asalnya',
    imageCaption: 'Deretan pahlawan nasional pada Rupiah TE 2022',
    interactionPrompt: 'Pahlawan nasional mana yang paling menginspirasimu pada pecahan uang Rupiah TE 2022?',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 4,
    contentOrder: 1,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'MAT-016',
    missionId: 'JR-B06',
    code: 'MAT-016',
    title: 'Kekayaan Tarian Tradisional & Flora Nusantara',
    summary: 'Ragam budaya yang ditampilkan pada bagian belakang uang kertas.',
    studentText: 'Sisi belakang uang Rupiah memadukan gerakan anggun tarian nusantara dengan keindahan bunga endemik Indonesia. Ada Tari Legong dari Bali bersanding dengan Bunga Jepun, Tari Gambyong dari Jawa, Tari Merak dari Jawa Barat dengan Anggrek Bulan, Tari Piring dari Minangkabau, hingga Tari Tifa dari Papua.',
    content: 'Sisi belakang uang Rupiah memadukan gerakan anggun tarian nusantara dengan keindahan bunga endemik Indonesia. Ada Tari Legong dari Bali bersanding dengan Bunga Jepun, Tari Gambyong dari Jawa, Tari Merak dari Jawa Barat dengan Anggrek Bulan, Tari Piring dari Minangkabau, hingga Tari Tifa dari Papua.',
    keyTakeaways: ['Menampilkan identitas seni budaya yang luhur', 'Kombinasi harmonis antara manusia dan alam Indonesia'],
    imageUrl: '',
    imageBrief: 'Ilustrasi penari tradisional dan bunga nusantara pada bagian belakang lembaran uang kertas Rupiah',
    imageCaption: 'Tarian dan keanekaragaman hayati nusantara',
    interactionPrompt: 'Tarian tradisional dari daerah manakah yang terdapat di pecahan uang Rupiah Rp50.000 atau Rp20.000?',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 3,
    contentOrder: 2,
    orderIndex: 2,
    status: 'published',
  },
  {
    id: 'MAT-017',
    missionId: 'JR-B06',
    code: 'MAT-017',
    title: 'Pariwisata & Lanskap Alam Indonesia pada Rupiah',
    summary: 'Mengagumi keindahan destinasi wisata unggulan di lembaran uang.',
    studentText: 'Keajaiban lanskap alam Nusantara seperti Kepulauan Raja Ampat di Papua Barat, Gunung Bromo di Jawa Timur, Taman Nasional Komodo di NTT, Kepulauan Banda Neira di Maluku, hingga Ngarai Sianok di Sumatera Barat diabadikan di lembaran Rupiah sebagai etalase pariwisata dunia.',
    content: 'Keajaiban lanskap alam Nusantara seperti Kepulauan Raja Ampat di Papua Barat, Gunung Bromo di Jawa Timur, Taman Nasional Komodo di NTT, Kepulauan Banda Neira di Maluku, hingga Ngarai Sianok di Sumatera Barat diabadikan di lembaran Rupiah sebagai etalase pariwisata dunia.',
    keyTakeaways: ['Memperkenalkan destinasi kelas dunia Indonesia', 'Membangkitkan kebanggaan pada kekayaan tanah air'],
    imageUrl: '',
    imageBrief: 'Kolase panorama alam ikonik nusantara yang tercantum pada uang kertas Rupiah TE 2022',
    imageCaption: 'Pemandangan alam ikonik Nusantara pada uang kertas',
    interactionPrompt: 'Destinasi wisata Indonesia mana yang terdapat di pecahan Rupiah yang paling ingin kamu kunjungi suatu hari nanti?',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 3,
    contentOrder: 3,
    orderIndex: 3,
    status: 'published',
  },

  // Misi 7 (2 Lessons) - JR-P07
  {
    id: 'MAT-018',
    missionId: 'JR-P07',
    code: 'MAT-018',
    title: 'Kecakapan Berhitung & Memeriksa Kembalian',
    summary: 'Keterampilan dasar bertransaksi tunai secara teliti dan jujur.',
    studentText: 'Saat berbelanja di kantin sekolah atau toko buku, biasakan berhitung dengan teliti. Ketahui harga barang sebelum membayar, siapkan uang pas jika memungkinkan, dan selalu hitung uang kembalian yang kamu terima di depan kasir sebelum melangkah pergi.',
    content: 'Saat berbelanja di kantin sekolah atau toko buku, biasakan berhitung dengan teliti. Ketahui harga barang sebelum membayar, siapkan uang pas jika memungkinkan, dan selalu hitung uang kembalian yang kamu terima di depan kasir sebelum melangkah pergi.',
    keyTakeaways: ['Teliti sebelum membayar dan hitung uang kembalian', 'Bersikap jujur dan sopan saat bertransaksi'],
    imageUrl: '',
    imageBrief: 'Ilustrasi siswa teliti menghitung uang kembalian saat berbelanja di kantin sekolah',
    imageCaption: 'Interaksi belanja yang tertib di kantin sekolah',
    interactionPrompt: 'Jika kamu membeli buku seharga Rp14.000 dan membayar dengan selembar uang Rp20.000, berapa uang kembalian yang harus kamu terima?',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 3,
    contentOrder: 1,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'MAT-019',
    missionId: 'JR-P07',
    code: 'MAT-019',
    title: 'Mengenal QRIS & Pembayaran Digital yang Aman',
    summary: 'Teknologi pembayaran masa kini yang Cepat, Mudah, Murah, Aman, dan Handal.',
    studentText: 'QRIS (Quick Response Code Indonesian Standard) adalah kode QR pembayaran resmi berstandar nasional yang diluncurkan Bank Indonesia. Dengan satu kode QRIS, kamu bisa membayar menggunakan berbagai aplikasi dompet digital atau mobile banking. Selalu periksa nama merchant dan nominal sebelum memasukkan PIN rahasiamu.',
    content: 'QRIS (Quick Response Code Indonesian Standard) adalah kode QR pembayaran resmi berstandar nasional yang diluncurkan Bank Indonesia. Dengan satu kode QRIS, kamu bisa membayar menggunakan berbagai aplikasi dompet digital atau mobile banking. Selalu periksa nama merchant dan nominal sebelum memasukkan PIN rahasiamu.',
    keyTakeaways: ['QRIS menyatukan seluruh kode QR pembayaran', 'Jaga kerahasiaan PIN dan konfirmasi nominal pembayaran'],
    imageUrl: '',
    imageBrief: 'Infografis logo resmi QRIS Bank Indonesia dan langkah aman bertransaksi digital (Cepat, Hemat, Aman, Handal)',
    imageCaption: 'Stiker logo resmi QRIS Bank Indonesia',
    interactionPrompt: 'Pernahkah kamu melihat logo QRIS di kantin sekolah atau toko sekitar rumahmu? Apa keunggulannya dibanding membawa banyak uang tunai?',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 4,
    contentOrder: 2,
    orderIndex: 2,
    status: 'published',
  },

  // Misi 8 (3 Lessons) - JR-P08
  {
    id: 'MAT-020',
    missionId: 'JR-P08',
    code: 'MAT-020',
    title: 'Membedakan Kebutuhan vs Keinginan',
    summary: 'Kunci utama mengelola keuangan agar tidak boros.',
    studentText: 'Kebutuhan adalah segala sesuatu yang mutlak diperlukan untuk hidup dan belajar (misalnya: makan sehat, seragam sekolah, buku tulis). Keinginan adalah hal-hal tambahan yang jika tidak terpenuhi, hidup dan belajar kita tetap berjalan normal (misalnya: mainan baru, sepatu mahal edisi terbatas). Dahulukan kebutuhan sebelum menuruti keinginan.',
    content: 'Kebutuhan adalah segala sesuatu yang mutlak diperlukan untuk hidup dan belajar (misalnya: makan sehat, seragam sekolah, buku tulis). Keinginan adalah hal-hal tambahan yang jika tidak terpenuhi, hidup dan belajar kita tetap berjalan normal (misalnya: mainan baru, sepatu mahal edisi terbatas). Dahulukan kebutuhan sebelum menuruti keinginan.',
    keyTakeaways: ['Kebutuhan bersifat wajib dan mendesak', 'Keinginan dapat ditunda atau dibatasi'],
    imageUrl: '',
    imageBrief: 'Ilustrasi timbangan cerdas membedakan Kebutuhan (Needs) vs Keinginan (Wants)',
    imageCaption: 'Matriks pemilahan kebutuhan vs keinginan',
    interactionPrompt: 'Sebutkan 3 barang yang termasuk kebutuhan belajarmu dan 2 barang yang sekadar keinginan!',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 4,
    contentOrder: 1,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'MAT-021',
    missionId: 'JR-P08',
    code: 'MAT-021',
    title: 'Membuat Rencana Belanja Cerdas (Shopping List)',
    summary: 'Langkah praktis sebelum pergi berbelanja perlengkapan sekolah.',
    studentText: 'Sebelum pergi berbelanja perlengkapan sekolah bersama orang tua, buatlah daftar belanja (shopping list) terlebih dahulu. Tuliskan barang prioritas dan perkirakan harganya. Daftar ini menjaga kita tidak tergoda membeli barang-barang yang tidak diperlukan (impulse buying).',
    content: 'Sebelum pergi berbelanja perlengkapan sekolah bersama orang tua, buatlah daftar belanja (shopping list) terlebih dahulu. Tuliskan barang prioritas dan perkirakan harganya. Daftar ini menjaga kita tidak tergoda membeli barang-barang yang tidak diperlukan (impulse buying).',
    keyTakeaways: ['Mencegah pembelian impulsif', 'Menghargai nilai uang yang diperoleh orang tua'],
    imageUrl: '',
    imageBrief: 'Ilustrasi buku catatan checklist belanja cerdas siswa dengan pensil dan kalkulator mini',
    imageCaption: 'Catatan daftar belanja perlengkapan sekolah',
    interactionPrompt: 'Coba buat contoh daftar belanja 3 perlengkapan sekolah yang paling kamu butuhkan semester ini!',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 3,
    contentOrder: 2,
    orderIndex: 2,
    status: 'published',
  },
  {
    id: 'MAT-022',
    missionId: 'JR-P08',
    code: 'MAT-022',
    title: 'Mengenal Konsep Manfaat & Nilai Barang',
    summary: 'Memilih barang berkualitas yang awet dipakai.',
    studentText: 'Barang yang terbaik bukanlah barang yang paling mahal, melainkan barang yang paling bermanfaat dan awet digunakan. Merawat tas, sepatu, dan alat tulis yang sudah kamu miliki agar tidak cepat rusak adalah cara paling hebat untuk menghargai kerja keras orang tuamu dalam mencari uang.',
    content: 'Barang yang terbaik bukanlah barang yang paling mahal, melainkan barang yang paling bermanfaat dan awet digunakan. Merawat tas, sepatu, dan alat tulis yang sudah kamu miliki agar tidak cepat rusak adalah cara paling hebat untuk menghargai kerja keras orang tuamu dalam mencari uang.',
    keyTakeaways: ['Fokus pada fungsi dan daya tahan barang', 'Merawat barang milik sendiri menghemat pengeluaran'],
    imageUrl: '',
    imageBrief: 'Ilustrasi siswa merapikan dan merawat peralatan sekolahnya dengan bangga dan tertib',
    imageCaption: 'Memanfaatkan barang sekolah dengan awet',
    interactionPrompt: 'Bagaimana caramu merawat buku dan tas sekolahmu agar awet dipakai hingga akhir tahun ajaran?',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 3,
    contentOrder: 3,
    orderIndex: 3,
    status: 'published',
  },

  // Misi 9 (2 Lessons) - JR-P09
  {
    id: 'MAT-023',
    missionId: 'JR-P09',
    code: 'MAT-023',
    title: 'Menabung Sejak Dini: Celengan & Tabungan SimPel',
    summary: 'Membangun kebiasaan menyisihkan uang di awal, bukan sisa belanja.',
    studentText: 'Rumus menabung yang benar adalah menyisihkan uang di AWAL saat menerima uang saku, bukan menabung dari sisa uang belanja di akhir hari: "Pendapatan - Tabungan = Belanja". Kamu juga bisa membuka Tabungan SimPel (Simpanan Pelajar) di bank yang bebas biaya administrasi bulanan dan memiliki buku tabungan atas namamu sendiri.',
    content: 'Rumus menabung yang benar adalah menyisihkan uang di AWAL saat menerima uang saku, bukan menabung dari sisa uang belanja di akhir hari: "Pendapatan - Tabungan = Belanja". Kamu juga bisa membuka Tabungan SimPel (Simpanan Pelajar) di bank yang bebas biaya administrasi bulanan dan memiliki buku tabungan atas namamu sendiri.',
    keyTakeaways: ['Sisihkan uang di awal saat menerima uang saku', 'Tabungan SimPel melatih disiplin berbank'],
    imageUrl: '',
    imageBrief: 'Ilustrasi celengan ayam lucu berdampingan dengan buku Tabungan SimPel Bank Indonesia',
    imageCaption: 'Buku Tabungan Simpanan Pelajar (SimPel)',
    interactionPrompt: 'Berapa rupiah yang ingin kamu sisihkan di awal setiap hari untuk dimasukkan ke celengan atau tabungan SimPel?',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 4,
    contentOrder: 1,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'MAT-024',
    missionId: 'JR-P09',
    code: 'MAT-024',
    title: 'Merancang Target Impian Masa Depan',
    summary: 'Mewujudkan impian dengan disiplin finansial berjangka.',
    studentText: 'Menabung akan terasa jauh lebih seru jika kamu memiliki target impian yang jelas, misalnya membeli sepeda, ensiklopedia sains, atau menyiapkan dana kuliah. Buatlah papan target (dream board) dan catat setiap kali kamu menabung. Disiplin finansial kecil setiap hari akan membawamu meraih impian besar di masa depan.',
    content: 'Menabung akan terasa jauh lebih seru jika kamu memiliki target impian yang jelas, misalnya membeli sepeda, ensiklopedia sains, atau menyiapkan dana kuliah. Buatlah papan target (dream board) dan catat setiap kali kamu menabung. Disiplin finansial kecil setiap hari akan membawamu meraih impian besar di masa depan.',
    keyTakeaways: ['Menetapkan tujuan membuat proses menabung lebih seru', 'Disiplin kecil hari ini menghasilkan pencapaian besar di masa depan'],
    imageUrl: '',
    imageBrief: 'Ilustrasi grafik target tabungan siswa mencapai impian masa depan dengan penuh semangat',
    imageCaption: 'Papan impian tabungan siswa',
    interactionPrompt: 'Apa impian terbesarmu yang ingin kamu wujudkan dengan hasil tabunganmu sendiri?',
    gradeScope: 'Semua Tingkat',
    contentType: 'article',
    readTimeMinutes: 3,
    contentOrder: 2,
    orderIndex: 2,
    status: 'published',
  },
];

export const seedActivities: Activity[] = [
  // 18 Aktivitas (2 per misi)
  {
    id: 'ACT-001',
    missionId: 'JR-C01',
    code: 'ACT-001',
    title: 'Detektif 3D: Cek Fitur Keaslian',
    type: 'interactive',
    instruction: 'Amati bagian uang kertas dan temukan 3 unsur pengaman: Watermark, Tinta Berubah Warna, dan Cetak Kasar.',
    scenarioData: { targetCount: 3, hint: 'Gunakan kaca pembesar virtual' },
    pointReward: 100,
    xpReward: 50,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'ACT-002',
    missionId: 'JR-C01',
    code: 'ACT-002',
    title: 'Tebak Asli vs Palsu',
    type: 'quiz',
    instruction: 'Pilih pecahan uang yang memiliki tanda air dan logo Bank Indonesia yang saling mengisi sempurna.',
    scenarioData: { options: ['Uang A', 'Uang B'], correct: 0 },
    pointReward: 100,
    xpReward: 50,
    orderIndex: 2,
    status: 'published',
  },
  {
    id: 'ACT-003',
    missionId: 'JR-C02',
    code: 'ACT-003',
    title: 'Simulator Interaktif 5J (Merawat Rupiah)',
    type: 'simulator_5j',
    instruction: 'Pilah tindakan yang benar untuk menghindari 5J: Jangan Dilipat, Dicoret, Distapler, Diremas, dan Dibasahi.',
    scenarioData: { rulesCount: 5 },
    pointReward: 150,
    xpReward: 100,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'ACT-004',
    missionId: 'JR-C02',
    code: 'ACT-004',
    title: 'Tata Dompet Rapi',
    type: 'sorter',
    instruction: 'Susun uang kertas berdasarkan nominal dari yang terkecil ke terbesar secara lurus tanpa terlipat.',
    scenarioData: { sequence: [1000, 2000, 5000, 10000, 20000, 50000, 100000] },
    pointReward: 100,
    xpReward: 60,
    orderIndex: 2,
    status: 'published',
  },
  {
    id: 'ACT-005',
    missionId: 'JR-C03',
    code: 'ACT-005',
    title: 'Inspektur Uang Layak Edar',
    type: 'sorter',
    instruction: 'Kelompokkan sampel uang ke dalam kotak Uang Layak Edar (ULE) atau Uang Tidak Layak Edar (UTLE).',
    scenarioData: { items: ['Uang bersih', 'Uang ada coretan spidol', 'Uang robek 3cm', 'Uang mulus'] },
    pointReward: 120,
    xpReward: 70,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'ACT-006',
    missionId: 'JR-C03',
    code: 'ACT-006',
    title: 'Simulasi Aplikasi PINTAR Bank Indonesia',
    type: 'interactive',
    instruction: 'Pilih lokasi kas keliling terdekat dan tentukan jumlah uang rusak yang akan ditukarkan.',
    scenarioData: { stepCount: 3 },
    pointReward: 100,
    xpReward: 50,
    orderIndex: 2,
    status: 'published',
  },
  {
    id: 'ACT-007',
    missionId: 'JR-B04',
    code: 'ACT-007',
    title: 'Puzzle Garuda & Frasa NKRI',
    type: 'interactive',
    instruction: 'Pasangkan potongan lambang Garuda Pancasila dan tulisan NKRI pada posisi yang tepat di uang kertas.',
    scenarioData: { pieces: 4 },
    pointReward: 110,
    xpReward: 60,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'ACT-008',
    missionId: 'JR-B04',
    code: 'ACT-008',
    title: 'Garis Waktu Sejarah ORI 1946',
    type: 'decision_quest',
    instruction: 'Urutkan peristiwa sejarah penerbitan Oeang Republik Indonesia dari Proklamasi hingga 30 Oktober 1946.',
    scenarioData: { steps: ['Proklamasi 1945', 'Rencana Mata Uang Sendiri', 'Penerbitan ORI 30 Okt 1946'] },
    pointReward: 120,
    xpReward: 70,
    orderIndex: 2,
    status: 'published',
  },
  {
    id: 'ACT-009',
    missionId: 'JR-B05',
    code: 'ACT-009',
    title: 'Studi Kasus: Transaksi di Pulau Perbatasan',
    type: 'decision_quest',
    instruction: 'Tentukan sikap yang benar ketika ada turis asing yang ingin membeli oleh-oleh lokal menggunakan uang asing.',
    scenarioData: { correctChoice: 'Mengarahkan turis menukar uang ke Rupiah di Money Changer resmi' },
    pointReward: 130,
    xpReward: 80,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'ACT-010',
    missionId: 'JR-B05',
    code: 'ACT-010',
    title: 'Kuis Kepatuhan UU Mata Uang',
    type: 'quiz',
    instruction: 'Jawab skenario hukum penggunaan Rupiah sesuai UU No. 7 Tahun 2011.',
    scenarioData: { questionsCount: 3 },
    pointReward: 100,
    xpReward: 60,
    orderIndex: 2,
    status: 'published',
  },
  {
    id: 'ACT-011',
    missionId: 'JR-B06',
    code: 'ACT-011',
    title: 'Mencocokkan Pahlawan & Pecahan Rupiah',
    type: 'sorter',
    instruction: 'Pasangkan foto pahlawan nasional dengan pecahan uang Rupiah TE 2022 yang sesuai.',
    scenarioData: { pairs: [['Ir. Soekarno', 'Rp100.000'], ['Ir. H. Djuanda', 'Rp50.000'], ['Frans Kaisiepo', 'Rp10.000']] },
    pointReward: 140,
    xpReward: 80,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'ACT-012',
    missionId: 'JR-B06',
    code: 'ACT-012',
    title: 'Peta Budaya & Destinasi Nusantara',
    type: 'interactive',
    instruction: 'Klik titik lokasi di peta Indonesia untuk melihat tarian dan tempat wisata yang tertera pada Rupiah.',
    scenarioData: { points: ['Raja Ampat', 'Danau Toba', 'Gunung Bromo', 'Banda Neira'] },
    pointReward: 120,
    xpReward: 70,
    orderIndex: 2,
    status: 'published',
  },
  {
    id: 'ACT-013',
    missionId: 'JR-P07',
    code: 'ACT-013',
    title: 'Kalkulator Cilik Kantin Sehat',
    type: 'interactive',
    instruction: 'Hitung total belanjaan makanan sehat dan tentukan lembaran uang serta kembalian yang benar.',
    scenarioData: { budget: 20000, items: [{ name: 'Nasi Kuning', price: 12000 }, { name: 'Jus Buah', price: 5000 }] },
    pointReward: 120,
    xpReward: 70,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'ACT-014',
    missionId: 'JR-P07',
    code: 'ACT-014',
    title: 'Simulasi Pembayaran QRIS Aman',
    type: 'decision_quest',
    instruction: 'Lakukan langkah pindai QRIS, periksa nama toko, masukkan nominal pas, dan jaga kerahasiaan PIN.',
    scenarioData: { steps: ['Buka Kamera Scan', 'Periksa Nama Merchant', 'Cek Nominal', 'Input PIN'] },
    pointReward: 130,
    xpReward: 80,
    orderIndex: 2,
    status: 'published',
  },
  {
    id: 'ACT-015',
    missionId: 'JR-P08',
    code: 'ACT-015',
    title: 'Pilah Kebutuhan vs Keinginan (Sort Challenge)',
    type: 'sorter',
    instruction: 'Tarik setiap kartu barang ke dalam keranjang "Kebutuhan Pokok" atau keranjang "Keinginan".',
    scenarioData: { items: ['Buku Tulis', 'Sepatu Sekolah', 'Mainan Robotik', 'Pensil 2B', 'Permen Lolipop'] },
    pointReward: 140,
    xpReward: 80,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'ACT-016',
    missionId: 'JR-P08',
    code: 'ACT-016',
    title: 'Penyusun Daftar Belanja Bijak',
    type: 'budget_planner',
    instruction: 'Kelola anggaran saku Rp30.000 agar kebutuhan sekolah terpenuhi dan masih ada uang sisa untuk ditabung.',
    scenarioData: { budget: 30000, requiredItems: ['Buku Gambar', 'Penggaris'] },
    pointReward: 150,
    xpReward: 90,
    orderIndex: 2,
    status: 'published',
  },
  {
    id: 'ACT-017',
    missionId: 'JR-P09',
    code: 'ACT-017',
    title: 'Celengan Target Impianku',
    type: 'interactive',
    instruction: 'Tentukan target tabungan dan simulasikan menabung Rp2.000 setiap hari hingga target tercapai.',
    scenarioData: { dailySaving: 2000, targetGoal: 50000 },
    pointReward: 150,
    xpReward: 90,
    orderIndex: 1,
    status: 'published',
  },
  {
    id: 'ACT-018',
    missionId: 'JR-P09',
    code: 'ACT-018',
    title: 'Petualangan Buka Rekening SimPel',
    type: 'decision_quest',
    instruction: 'Lengkapi formulir pembukaan tabungan Simpanan Pelajar dan tandatangani buku tabungan pertamamu.',
    scenarioData: { initialDeposit: 5000 },
    pointReward: 160,
    xpReward: 100,
    orderIndex: 2,
    status: 'published',
  },
];

// Helper to generate full 110 Practice Questions across 9 missions
function generatePracticeQuestions(): PracticeQuestion[] {
  const list: PracticeQuestion[] = [];
  
  const missionCategories = [
    { mId: 'JR-C01', cat: 'Ciri Keaslian Rupiah (3D)' },
    { mId: 'JR-C02', cat: 'Prinsip 5J Merawat Rupiah' },
    { mId: 'JR-C03', cat: 'Uang Layak Edar & Penukaran' },
    { mId: 'JR-B04', cat: 'Rupiah Simbol Kedaulatan' },
    { mId: 'JR-B05', cat: 'Alat Pembayaran Sah & UU' },
    { mId: 'JR-B06', cat: 'Pemersatu Bangsa & Budaya' },
    { mId: 'JR-P07', cat: 'Cerdas Bertransaksi & QRIS' },
    { mId: 'JR-P08', cat: 'Kebutuhan vs Keinginan' },
    { mId: 'JR-P09', cat: 'Menabung & Simpanan Pelajar' },
  ];

  // Specific canonical questions
  const canonicalQuestions = [
    // JR-C01 (QST-001 to QST-012)
    {
      mId: 'JR-C01',
      q: 'Apa yang dimaksud dengan metode 3D dalam mengenali keaslian uang Rupiah?',
      opts: ['Dilihat, Diraba, Diterawang', 'Disimpan, Dirawat, Digunakan', 'Dihitung, Ditabung, Dibelanjakan', 'Dipajang, Difoto, Dibagikan'],
      ans: 0,
      exp: 'Metode 3D adalah cara resmi mengenali uang Rupiah asli: Dilihat warnanya, Diraba tekstur kasarnya, dan Diterawang tanda airnya.',
      diff: 'easy' as const,
    },
    {
      mId: 'JR-C01',
      q: 'Saat meraba uang kertas asli pada bagian lambang Garuda dan angka nominal, apa yang kita rasakan?',
      opts: ['Permukaan sangat licin dan tipis', 'Tekstur terasa kasar karena teknik cetak intaglio', 'Permukaan terasa berair', 'Permukaan terasa lengket'],
      ans: 1,
      exp: 'Uang kertas asli menggunakan teknik cetak intaglio khusus yang menghasilkan sensasi rabaan kasar pada gambar utama dan nominal.',
      diff: 'easy' as const,
    },
    {
      mId: 'JR-C01',
      q: 'Fitur apakah yang terlihat saat uang Rupiah kertas diterawang ke arah sumber cahaya?',
      opts: ['Tanda air (watermark) pahlawan dan electrotype', 'Nomor rekening bank', 'Kode barcode belanja', 'Tanda tangan pemilik toko'],
      ans: 0,
      exp: 'Tanda air bergambar pahlawan dan logo electrotype akan tampak jelas dan tiga dimensi saat uang diterawang.',
      diff: 'medium' as const,
    },
    {
      mId: 'JR-C01',
      q: 'Apa keunggulan uang Rupiah Tahun Emisi 2022 dibandingkan emisi sebelumnya?',
      opts: ['Warna lebih buram dan mudah robek', 'Memiliki lapisan pelindung (varnish) sehingga lebih tahan lama dan warna lebih tajam', 'Ukurannya jauh lebih besar dari dompet', 'Tidak memiliki gambar pahlawan'],
      ans: 1,
      exp: 'Uang TE 2022 dilengkapi lapisan varnish untuk meningkatkan masa edar dan daya tahan kertas terhadap cairan/kotoran.',
      diff: 'medium' as const,
    },
    {
      mId: 'JR-C01',
      q: 'Mengapa terdapat selisih ukuran panjang 5 mm antar pecahan uang kertas TE 2022?',
      opts: ['Hanya untuk hiasan', 'Memudahkan masyarakat dan penyandang tunanetra membedakan pecahan uang', 'Agar hemat kertas', 'Menyesuaikan ukuran saku baju'],
      ans: 1,
      exp: 'Selisih ukuran 5 mm membantu pembedaan nominal secara taktil, terutama bagi tunanetra (blind code).',
      diff: 'easy' as const,
    },
    {
      mId: 'JR-C01',
      q: 'Unsur pengaman berupa benang yang dianyam pada uang kertas disebut...',
      opts: ['Benang jahit baju', 'Benang pengaman (security thread)', 'Tali pita kado', 'Garis tepi'],
      ans: 1,
      exp: 'Benang pengaman berpendar dan berubah warna ketika dilihat dari sudut pandang berbeda.',
      diff: 'medium' as const,
    },
    {
      mId: 'JR-C01',
      q: 'Logo Bank Indonesia yang terlihat menyatu utuh di kedua sisi saat diterawang disebut...',
      opts: ['Rectoverso (gambar saling mengisi)', 'Latent image', 'Microtext', 'Watermark'],
      ans: 0,
      exp: 'Rectoverso adalah gambar ornamen logo BI yang dicetak terpisah di depan dan belakang namun menyatu sempurna saat diterawang.',
      diff: 'hard' as const,
    },
    {
      mId: 'JR-C01',
      q: 'Apa yang harus dilakukan jika menemukan uang yang dicurigai tidak asli (palsu)?',
      opts: ['Membelanjakannya cepat-cepat', 'Melaporkan dan menyerahkannya ke kantor polisi atau bank terdekat untuk diverifikasi', 'Merobeknya sendiri', 'Menjualnya ke teman'],
      ans: 1,
      exp: 'Uang yang dicurigai palsu harus dilaporkan ke pihak berwajib atau bank untuk diproses sesuai hukum.',
      diff: 'easy' as const,
    },

    // JR-C02 (QST-013 to QST-025)
    {
      mId: 'JR-C02',
      q: 'Manakah yang termasuk dalam prinsip 5J merawat uang Rupiah?',
      opts: ['Jangan Dilipat, Jangan Dicoret, Jangan Distapler, Jangan Diremas, Jangan Dibasahi', 'Jangan Diberikan, Jangan Dipakai, Jangan Dihitung, Jangan Dibeli, Jangan Dijual', 'Jangan Ditabung, Jangan Disimpan, Jangan Dirawat, Jangan Ditukar, Jangan Dirapikan', 'Jangan Dilihat, Jangan Diraba, Jangan Diterawang, Jangan Dipegang, Jangan Disentuh'],
      ans: 0,
      exp: '5J adalah panduan resmi Bank Indonesia: Jangan Dilipat, Jangan Dicoret, Jangan Distapler, Jangan Diremas, Jangan Dibasahi.',
      diff: 'easy' as const,
    },
    {
      mId: 'JR-C02',
      q: 'Mengapa kita tidak boleh menstapler uang kertas?',
      opts: ['Karena membuat uang terlihat lebih indah', 'Karena jarum staples melubangi, merobek serat, dan meninggalkan noda karat', 'Karena jarum staples membuat uang semakin kuat', 'Karena staples gratis'],
      ans: 1,
      exp: 'Staples merusak serat kertas uang dan meninggalkan lubang serta karat yang mempercepat kerusakan uang.',
      diff: 'easy' as const,
    },
    {
      mId: 'JR-C02',
      q: 'Bagaimana cara terbaik menyimpan uang kertas agar tetap rapi dan tidak berkerut?',
      opts: ['Menggulung dan mengikatnya dengan karet ketat', 'Menyimpan lurus dalam dompet panjang yang bersih', 'Meremasnya ke dalam saku celana', 'Menyelipkannya di dalam sepatu'],
      ans: 1,
      exp: 'Menyimpan dalam dompet panjang menjaga fisik uang tetap lurus, bersih, dan tidak terlipat tajam.',
      diff: 'easy' as const,
    },
    {
      mId: 'JR-C02',
      q: 'Mengapa mencoret-coret uang Rupiah dengan pulpen dilarang keras?',
      opts: ['Merusak kebersihan, menutupi unsur pengaman, dan merendahkan simbol negara', 'Membuat uang bernilai lebih tinggi', 'Memudahkan pencatatan hutang', 'Sebagai tanda kepemilikan pribadi'],
      ans: 0,
      exp: 'Uang adalah simbol negara dan alat pembayaran publik, mencoretnya merusak fungsi pengamanan dan estetika.',
      diff: 'medium' as const,
    },
    {
      mId: 'JR-C02',
      q: 'Apa dampak jika uang kertas sering diremas di dalam saku?',
      opts: ['Uang menjadi lebih tebal', 'Kertas cepat lusuh, kusut, dan tidak bisa terbaca oleh mesin setor tunai ATM', 'Nominal uang bertambah', 'Uang berubah menjadi koin'],
      ans: 1,
      exp: 'Uang yang kusut/diremas mempersulit identifikasi sensor mesin ATM dan memperpendek masa edar uang.',
      diff: 'easy' as const,
    },
    {
      mId: 'JR-C02',
      q: 'Jika tangan kita basah atau berminyak setelah makan, apa yang sebaiknya dilakukan sebelum memegang uang?',
      opts: ['Langsung memegang uang agar wangi', 'Mencuci dan mengeringkan tangan terlebih dahulu', 'Mengeringkan tangan di atas lembaran uang', 'Membasahi seluruh uang'],
      ans: 1,
      exp: 'Keringkan tangan sebelum memegang uang agar zat cair dan minyak tidak menempel di kertas uang.',
      diff: 'easy' as const,
    },

    // JR-C03
    {
      mId: 'JR-C03',
      q: 'Apa yang dimaksud dengan Uang Layak Edar (ULE)?',
      opts: ['Uang mainan yang bergambar kartun', 'Uang Rupiah asli yang memenuhi standar kualitas bersih dan tidak rusak untuk diedarkan', 'Uang palsu yang sudah dicap', 'Uang kuno yang sudah tidak berlaku'],
      ans: 1,
      exp: 'ULE adalah uang asli yang kondisi fisiknya masih prima dan layak digunakan untuk transaksi masyarakat sehari-hari.',
      diff: 'easy' as const,
    },
    {
      mId: 'JR-C03',
      q: 'Uang yang telah sobek lebih dari setengah bagian atau terbakar termasuk dalam kategori...',
      opts: ['Uang Layak Edar', 'Uang Sangat Bagus', 'Uang Tidak Layak Edar (Uang Rusak)', 'Uang Peringatan'],
      ans: 2,
      exp: 'Uang rusak atau sobek parah diklasifikasikan sebagai Uang Tidak Layak Edar (UTLE).',
      diff: 'easy' as const,
    },
    {
      mId: 'JR-C03',
      q: 'Di manakah masyarakat dapat menukarkan uang rusak atau uang lusuh dengan uang yang baru?',
      opts: ['Di kantor Bank Indonesia, kas keliling resmi, atau loket perbankan umum', 'Di pasar loak', 'Di tempat pembuangan sampah', 'Di toko mainan'],
      ans: 0,
      exp: 'Bank Indonesia dan bank umum menyediakan layanan penukaran uang lusuh dan rusak secara gratis.',
      diff: 'medium' as const,
    },
    {
      mId: 'JR-C03',
      q: 'Layanan daring milik Bank Indonesia untuk pemesanan jadwal penukaran uang adalah...',
      opts: ['Aplikasi PINTAR (pintar.bi.go.id)', 'Aplikasi Belanja Online', 'Aplikasi Pesan Makanan', 'Aplikasi Game Online'],
      ans: 0,
      exp: 'Aplikasi PINTAR adalah portal resmi BI untuk melayani penukaran uang secara terjadwal.',
      diff: 'medium' as const,
    },

    // JR-B04
    {
      mId: 'JR-B04',
      q: 'Mengapa Rupiah disebut sebagai salah satu Simbol Kedaulatan Negara Republik Indonesia?',
      opts: ['Karena hanya berlaku di satu kota saja', 'Karena Rupiah menandai kedaulatan hukum dan kemandirian ekonomi NKRI sejajar dengan lambang negara lainnya', 'Karena Rupiah dibuat dari emas murni', 'Karena Rupiah bisa dicetak oleh siapa saja'],
      ans: 1,
      exp: 'Rupiah mencerminkan martabat bangsa merdeka dan identitas kedaulatan wilayah NKRI.',
      diff: 'medium' as const,
    },
    {
      mId: 'JR-B04',
      q: 'Setiap tanggal berapa bangsa Indonesia memperingati Hari Oeang Republik Indonesia (HORI)?',
      opts: ['17 Agustus', '30 Oktober', '10 November', '21 April'],
      ans: 1,
      exp: '30 Oktober 1946 adalah tanggal pertama kali ORI resmi beredar menggantikan uang NICA dan uang Jepang.',
      diff: 'medium' as const,
    },
    {
      mId: 'JR-B04',
      q: 'Tanda tangan siapakah yang tertera pada uang kertas Rupiah Tahun Emisi 2022?',
      opts: ['Presiden RI dan Wakil Presiden RI', 'Gubernur Bank Indonesia dan Menteri Keuangan Republik Indonesia', 'Kepala Sekolah dan Guru Kelas', 'Gubernur Daerah dan Walikota'],
      ans: 1,
      exp: 'Sesuai UU Mata Uang, uang Rupiah ditandatangani oleh Gubernur BI dan Menteri Keuangan RI mewakili pemerintah.',
      diff: 'hard' as const,
    },

    // JR-B05
    {
      mId: 'JR-B05',
      q: 'Undang-Undang nomor berapakah yang mengatur tentang Mata Uang Rupiah di Indonesia?',
      opts: ['UU No. 7 Tahun 2011', 'UU No. 1 Tahun 2020', 'UU No. 5 Tahun 1999', 'UU No. 12 Tahun 2005'],
      ans: 0,
      exp: 'UU No. 7 Tahun 2011 adalah payung hukum utama yang menegaskan kewajiban penggunaan Rupiah di NKRI.',
      diff: 'hard' as const,
    },
    {
      mId: 'JR-B05',
      q: 'Apakah seseorang di Indonesia boleh menolak pembayaran barang dengan uang Rupiah yang asli dan sah?',
      opts: ['Boleh, jika penjual lebih suka uang dolar', 'Tidak boleh, karena menolak Rupiah yang sah di wilayah NKRI melanggar undang-undang', 'Boleh jika pembeli masih anak-anak', 'Boleh kapan saja tanpa alasan'],
      ans: 1,
      exp: 'Setiap pihak di wilayah NKRI dilarang menolak Rupiah yang sah kecuali ada keraguan atas keasliannya.',
      diff: 'medium' as const,
    },
    {
      mId: 'JR-B05',
      q: 'Mengapa kita harus bangga menggunakan Rupiah saat bertransaksi di dalam negeri?',
      opts: ['Untuk memperkuat stabilitas nilai tukar Rupiah dan mendukung kemandirian ekonomi bangsa', 'Agar terlihat hebat di depan teman', 'Karena tidak ada uang lain di dunia', 'Supaya tidak perlu membayar'],
      ans: 0,
      exp: 'Penggunaan Rupiah secara konsisten menjaga stabilitas ekonomi dan nilai mata uang kita.',
      diff: 'easy' as const,
    },

    // JR-B06
    {
      mId: 'JR-B06',
      q: 'Tokoh pahlawan nasional siapakah yang fotonya tercantum pada pecahan uang kertas Rp100.000?',
      opts: ['Ir. Soekarno dan Drs. Mohammad Hatta', 'Pangeran Diponegoro', 'R.A. Kartini', 'Jenderal Sudirman'],
      ans: 0,
      exp: 'Proklamator kemerdekaan Ir. Soekarno dan Drs. Mohammad Hatta menghiasi pecahan Rp100.000.',
      diff: 'easy' as const,
    },
    {
      mId: 'JR-B06',
      q: 'Pahlawan asal Papua yang fotonya tertera pada pecahan uang kertas Rp10.000 TE 2022 adalah...',
      opts: ['Frans Kaisiepo', 'Pattimura', 'Tuanku Imam Bonjol', 'Sisingamangaraja XII'],
      ans: 0,
      exp: 'Frans Kaisiepo adalah pahlawan nasional dari Papua yang terpampang pada uang kertas Rp10.000.',
      diff: 'medium' as const,
    },
    {
      mId: 'JR-B06',
      q: 'Destinasi wisata kepulauan indah di Papua Barat yang tertera pada uang kertas Rp100.000 adalah...',
      opts: ['Raja Ampat', 'Candi Borobudur', 'Danau Toba', 'Pantai Kuta'],
      ans: 0,
      exp: 'Keindahan alam Raja Ampat diabadikan pada sisi belakang pecahan Rp100.000 TE 2022.',
      diff: 'easy' as const,
    },

    // JR-P07
    {
      mId: 'JR-P07',
      q: 'Jika Budi membeli buku seharga Rp13.500 dan membayar dengan uang Rp20.000, berapakah kembalian yang harus diterima Budi?',
      opts: ['Rp5.500', 'Rp6.500', 'Rp7.500', 'Rp4.500'],
      ans: 1,
      exp: 'Rp20.000 - Rp13.500 = Rp6.500 kembalian yang tepat.',
      diff: 'easy' as const,
    },
    {
      mId: 'JR-P07',
      q: 'Apa kepanjangan dari QRIS sebagai metode pembayaran non-tunai di Indonesia?',
      opts: ['Quick Response Code Indonesian Standard', 'Quick Receipt Indonesian System', 'Quality Retail Indonesian Store', 'Quick Rupiah Internet Service'],
      ans: 0,
      exp: 'QRIS adalah Quick Response Code Indonesian Standard yang diluncurkan oleh Bank Indonesia.',
      diff: 'medium' as const,
    },
    {
      mId: 'JR-P07',
      q: 'Apa yang harus dijaga kerahasiaannya saat melakukan transaksi pembayaran digital?',
      opts: ['Nama sekolah', 'PIN dan Kode OTP transaksi', 'Warna seragam', 'Jumlah teman sekelas'],
      ans: 1,
      exp: 'PIN dan OTP adalah kunci keamanan pribadi yang tidak boleh dibagikan kepada siapapun.',
      diff: 'easy' as const,
    },

    // JR-P08
    {
      mId: 'JR-P08',
      q: 'Manakah di bawah ini yang merupakan contoh "Kebutuhan Pokok" bagi seorang pelajar?',
      opts: ['Buku pelajaran dan pensil', 'Mainan remote control mahal', 'Baju pesta model terbaru', 'Koleksi kartu game impor'],
      ans: 0,
      exp: 'Buku dan alat tulis adalah kebutuhan utama untuk belajar di sekolah.',
      diff: 'easy' as const,
    },
    {
      mId: 'JR-P08',
      q: 'Sikap "Paham Berbelanja" yang bijak ketika melihat barang diskon yang tidak dibutuhkan adalah...',
      opts: ['Membeli sebanyak-banyaknya mumpung diskon', 'Menahan diri dan tidak membeli karena barang tersebut bukan kebutuhan', 'Meminjam uang teman untuk membeli', 'Menangis di toko'],
      ans: 1,
      exp: 'Generasi cerdas finansial hanya membeli apa yang dibutuhkan, bukan tergiur diskon semata.',
      diff: 'easy' as const,
    },
    {
      mId: 'JR-P08',
      q: 'Apa manfaat membuat daftar belanja (shopping list) sebelum pergi ke toko buku?',
      opts: ['Supaya belanja lebih lama', 'Menjaga pengeluaran tetap terkontrol dan mencegah membeli barang yang tidak perlu', 'Agar kasir toko bingung', 'Supaya tas belanja lebih berat'],
      ans: 1,
      exp: 'Daftar belanja membantu kita fokus membeli barang yang benar-benar dibutuhkan.',
      diff: 'easy' as const,
    },

    // JR-P09
    {
      mId: 'JR-P09',
      q: 'Kapan waktu terbaik untuk menyisihkan uang tabungan dari uang saku?',
      opts: ['Di akhir bulan jika masih ada sisa', 'Di awal saat pertama kali menerima uang saku', 'Hanya saat disuruh guru', 'Saat uang saku sudah habis'],
      ans: 1,
      exp: 'Menabung di awal memastikan tabungan selalu terisi sebelum uang saku dibelanjakan.',
      diff: 'easy' as const,
    },
    {
      mId: 'JR-P09',
      q: 'Apa nama produk tabungan khusus untuk pelajar di perbankan Indonesia yang bebas biaya admin?',
      opts: ['Tabungan SimPel (Simpanan Pelajar)', 'Tabungan Masa Depan Emas', 'Kredit Usaha Rakyat', 'Giro Bisnis'],
      ans: 0,
      exp: 'Tabungan SimPel (Simpanan Pelajar) dirancang khusus untuk siswa dengan persyaratan mudah dan setoran ringan.',
      diff: 'easy' as const,
    },
    {
      mId: 'JR-P09',
      q: 'Apa manfaat memiliki tujuan atau impian saat menabung di celengan?',
      opts: ['Membuat kita lebih bersemangat, disiplin, dan teratur menyisihkan uang', 'Agar celengan cepat rusak', 'Supaya bisa pamer uang ke teman', 'Agar tidak perlu belajar lagi'],
      ans: 0,
      exp: 'Memiliki target yang jelas melatih ketekunan dan kesabaran meraih impian.',
      diff: 'easy' as const,
    },
  ];

  // Insert canonical questions first
  let qCounter = 1;
  for (const cq of canonicalQuestions) {
    const code = `QST-${String(qCounter).padStart(3, '0')}`;
    const id = code;
    const cat = missionCategories.find((m) => m.mId === cq.mId)?.cat || 'Edukasi Rupiah';
    list.push({
      id,
      missionId: cq.mId,
      code,
      question: cq.q,
      options: cq.opts,
      correctAnswerIndex: cq.ans,
      explanation: cq.exp,
      difficulty: cq.diff,
      competencyCategory: cat,
      status: 'published',
    });
    qCounter++;
  }

  // Populate remaining questions systematically up to exact 110 items
  // Distributing fairly across 9 missions (approx 12-13 questions per mission)
  while (qCounter <= 110) {
    const mIdx = (qCounter - 1) % 9;
    const mission = seedMissions[mIdx];
    const cat = missionCategories[mIdx].cat;
    const code = `QST-${String(qCounter).padStart(3, '0')}`;
    const id = code;

    const sampleTopics = [
      {
        q: `Dalam pembelajaran ${mission.title}, hal mendasar yang harus diperhatikan adalah...`,
        opts: [
          'Memahami nilai dan fungsi Rupiah dengan penuh tanggung jawab',
          'Mengabaikan aturan penggunaan uang yang sah',
          'Mengutamakan uang asing di dalam negeri',
          'Menyimpan uang di tempat yang lembab',
        ],
        ans: 0,
        exp: `Pada misi ${mission.title}, siswa diajarkan untuk menghargai dan mengelola Rupiah secara beretika.`,
      },
      {
        q: `Pernyataan yang paling tepat mengenai ${mission.subtitle} adalah...`,
        opts: [
          'Membantu meningkatkan kecakapan literasi finansial generasi muda Indonesia',
          'Hanya berlaku untuk orang dewasa yang bekerja di perbankan',
          'Tidak memiliki dampak bagi kehidupan sehari-hari',
          'Hanya perlu dipelajari saat ujian sekolah',
        ],
        ans: 0,
        exp: `Literasi mengenai ${mission.subtitle} relevan diterapkan oleh seluruh siswa sekolah dasar sejak dini.`,
      },
      {
        q: `Contoh penerapan nyata dari ${mission.title} di lingkungan sekolah adalah...`,
        opts: [
          'Membiasakan diri bersikap tertib, cermat, dan peduli kebersihan uang di kantin dan kelas',
          'Mencoret uang jajan dengan nama sendiri',
          'Menghabiskan seluruh uang saku sebelum jam istirahat',
          'Melipat uang menjadi mainan origami',
        ],
        ans: 0,
        exp: `Penerapan positif ${mission.title} tercermin dalam perilaku sehari-hari yang menghormati mata uang Rupiah.`,
      },
    ];

    const pick = sampleTopics[(qCounter + mIdx) % sampleTopics.length];

    list.push({
      id,
      missionId: mission.id,
      code,
      question: `${pick.q} (Soal #${qCounter})`,
      options: pick.opts,
      correctAnswerIndex: pick.ans,
      explanation: pick.exp,
      difficulty: qCounter % 3 === 0 ? 'hard' : qCounter % 2 === 0 ? 'medium' : 'easy',
      competencyCategory: cat,
      status: 'published',
    });
    qCounter++;
  }

  return list;
}

export const seedPracticeQuestions: PracticeQuestion[] = generatePracticeQuestions();

export const seedBadges: Badge[] = [
  {
    id: 'BDG-01',
    missionId: 'JR-C01',
    code: 'BDG-01',
    name: 'Sahabat Rupiah',
    category: 'cinta',
    icon: 'search',
    color: '#EF4444',
    bgColor: '#FEE2E2',
    borderColor: '#FCA5A5',
    description: 'Menguasai metode 3D (Dilihat, Diraba, Diterawang) untuk mengidentifikasi keaslian uang Rupiah.',
    unlocked: true,
    unlockedDate: '10 Agustus 2026',
    xpReward: 150,
    status: 'published',
  },
  {
    id: 'BDG-02',
    missionId: 'JR-C02',
    code: 'BDG-02',
    name: 'Penjaga Rupiah',
    category: 'cinta',
    icon: 'shield-check',
    color: '#10B981',
    bgColor: '#D1FAE5',
    borderColor: '#6EE7B7',
    description: 'Menguasai 5 larangan merusak uang: Jangan Dilipat, Dicoret, Distapler, Diremas, dan Dibasahi.',
    unlocked: true,
    unlockedDate: '12 Agustus 2026',
    xpReward: 200,
    status: 'published',
  },
  {
    id: 'BDG-03',
    missionId: 'JR-C03',
    code: 'BDG-03',
    name: 'Detektif Rupiah',
    category: 'cinta',
    icon: 'sparkles',
    color: '#3B82F6',
    bgColor: '#DBEAFE',
    borderColor: '#93C5FD',
    description: 'Mampu membedakan uang layak edar dan memahami prosedur penukaran uang rusak di Bank Indonesia.',
    unlocked: true,
    unlockedDate: '14 Agustus 2026',
    xpReward: 250,
    status: 'published',
  },
  {
    id: 'BDG-04',
    missionId: 'JR-B04',
    code: 'BDG-04',
    name: 'Garuda Rupiah',
    category: 'bangga',
    icon: 'shield',
    color: '#8B5CF6',
    bgColor: '#EDE9FE',
    borderColor: '#C4B5FD',
    description: 'Menghayati Rupiah sebagai lambang kedaulatan NKRI dan tonggak kemandirian bangsa sejak ORI 1946.',
    unlocked: true,
    unlockedDate: '15 Agustus 2026',
    xpReward: 180,
    status: 'published',
  },
  {
    id: 'BDG-05',
    missionId: 'JR-B05',
    code: 'BDG-05',
    name: 'Bangga Rupiah',
    category: 'bangga',
    icon: 'coins',
    color: '#06B6D4',
    bgColor: '#CFFAFE',
    borderColor: '#67E8F9',
    description: 'Menjunjung kewajiban penggunaan Rupiah sebagai satu-satunya alat pembayaran yang sah di wilayah Indonesia.',
    unlocked: false,
    xpReward: 220,
    status: 'published',
  },
  {
    id: 'BDG-06',
    missionId: 'JR-B06',
    code: 'BDG-06',
    name: 'Sahabat Nusantara',
    category: 'bangga',
    icon: 'crown',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    borderColor: '#FCD34D',
    description: 'Mengenal seluruh pahlawan nasional, tarian daerah, dan keindahan alam yang diabadikan pada lembaran Rupiah.',
    unlocked: false,
    xpReward: 280,
    status: 'published',
  },
  {
    id: 'BDG-07',
    missionId: 'JR-P07',
    code: 'BDG-07',
    name: 'Transaksi Cerdas',
    category: 'paham',
    icon: 'receipt',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    borderColor: '#F472B6',
    description: 'Terampil menghitung kembalian uang dengan teliti dan paham bertransaksi digital aman dengan QRIS.',
    unlocked: false,
    xpReward: 150,
    status: 'published',
  },
  {
    id: 'BDG-08',
    missionId: 'JR-P08',
    code: 'BDG-08',
    name: 'Pembeli Cerdas',
    category: 'paham',
    icon: 'shopping-cart',
    color: '#14B8A6',
    bgColor: '#CCFBF1',
    borderColor: '#5EEAD4',
    description: 'Mampu membedakan kebutuhan dan keinginan serta membuat rencana belanja yang rasional.',
    unlocked: false,
    xpReward: 200,
    status: 'published',
  },
  {
    id: 'BDG-09',
    missionId: 'JR-P09',
    code: 'BDG-09',
    name: 'Penabung Hebat',
    category: 'paham',
    icon: 'piggy-bank',
    color: '#EAB308',
    bgColor: '#FEF08A',
    borderColor: '#FACC15',
    description: 'Disiplin menyisihkan uang saku sejak dini untuk mewujudkan impian masa depan.',
    unlocked: false,
    xpReward: 300,
    status: 'published',
  },
];

export const seedReflections: Reflection[] = [
  {
    id: 'RFL-01',
    missionId: 'JR-C01',
    code: 'RFL-01',
    prompt: 'Bagaimana perasaanmu setelah berhasil mempraktikkan metode 3D pada uang Rupiah aslimu sendiri?',
    guideQuestions: [
      'Fitur pengaman apa yang paling menarik menurutmu?',
      'Apakah kamu akan mengajarkan metode 3D ini kepada keluargamu?',
    ],
    rubric: 'Menyebutkan minimal 2 fitur 3D dan komitmen berbagi ilmu.',
    status: 'published',
  },
  {
    id: 'RFL-02',
    missionId: 'JR-C02',
    code: 'RFL-02',
    prompt: 'Ceritakan satu kebiasaan merawat uang yang akan kamu ubah mulai hari ini setelah mempelajari prinsip 5J!',
    guideQuestions: [
      'Dari 5J, larangan mana yang paling sering kamu temui di sekitar?',
      'Langkah apa yang kamu lakukan agar uang sakumu tidak kusut?',
    ],
    rubric: 'Menyebutkan prinsip 5J dan solusi penyimpanan yang rapi.',
    status: 'published',
  },
  {
    id: 'RFL-03',
    missionId: 'JR-C03',
    code: 'RFL-03',
    prompt: 'Mengapa menjaga kebersihan uang yang beredar di masyarakat adalah tanggung jawab kita bersama?',
    guideQuestions: [
      'Apa yang kamu lakukan jika melihat uang kembalian yang robek?',
      'Bagaimana perasaan pedagang jika menerima uang yang bersih dan rapi?',
    ],
    rubric: 'Menjelaskan dampak positif uang bersih bagi kenyamanan transaksi.',
    status: 'published',
  },
  {
    id: 'RFL-04',
    missionId: 'JR-B04',
    code: 'RFL-04',
    prompt: 'Mengapa kita harus bangga bahwa bangsa Indonesia memiliki mata uang Rupiah sendiri?',
    guideQuestions: [
      'Apa makna perjuangan penerbitan ORI pada tahun 1946 bagi kemerdekaan kita?',
      'Bagaimana caramu menunjukkan rasa bangga terhadap simbol negara?',
    ],
    rubric: 'Menghubungkan kemerdekaan bangsa dengan kedaulatan Rupiah.',
    status: 'published',
  },
  {
    id: 'RFL-05',
    missionId: 'JR-B05',
    code: 'RFL-05',
    prompt: 'Jika kamu berkunjung ke daerah perbatasan Indonesia, mengapa penting selalu menggunakan Rupiah?',
    guideQuestions: [
      'Bagaimana penggunaan Rupiah melindungi wilayah NKRI?',
      'Apa yang akan kamu sampaikan jika ada teman yang ingin memakai mata uang asing di toko lokal?',
    ],
    rubric: 'Menjelaskan kewajiban hukum dan fungsi pertahanan ekonomi.',
    status: 'published',
  },
  {
    id: 'RFL-06',
    missionId: 'JR-B06',
    code: 'RFL-06',
    prompt: 'Pahlawan nasional atau tarian daerah mana pada pecahan Rupiah yang paling menginspirasimu?',
    guideQuestions: [
      'Nilai keteladanan apa yang bisa kamu contoh dari pahlawan tersebut?',
      'Mengapa keberagaman budaya pada uang Rupiah memperkuat persatuan kita?',
    ],
    rubric: 'Menyebutkan nama pahlawan dan nilai teladan persatuan bangsa.',
    status: 'published',
  },
  {
    id: 'RFL-07',
    missionId: 'JR-P07',
    code: 'RFL-07',
    prompt: 'Pengalaman berharga apa yang kamu dapatkan saat belajar menghitung kembalian dan mencoba transaksi non-tunai?',
    guideQuestions: [
      'Mengapa sikap teliti dan jujur sangat penting saat berbelanja?',
      'Aturan keamanan apa yang selalu kamu ingat saat menggunakan QRIS?',
    ],
    rubric: 'Menjelaskan ketelitian berhitung dan keamanan data pribadi.',
    status: 'published',
  },
  {
    id: 'RFL-08',
    missionId: 'JR-P08',
    code: 'RFL-08',
    prompt: 'Tuliskan satu contoh keputusan belanja bijak yang berhasil kamu buat minggu ini!',
    guideQuestions: [
      'Bagaimana kamu berhasil menahan diri dari godaan membeli barang keinginan?',
      'Apa manfaat yang kamu rasakan setelah memprioritaskan kebutuhan sekolah?',
    ],
    rubric: 'Membedakan kebutuhan vs keinginan dalam kehidupan nyata.',
    status: 'published',
  },
  {
    id: 'RFL-09',
    missionId: 'JR-P09',
    code: 'RFL-09',
    prompt: 'Apa impian terbesarmu yang ingin kamu capai melalui disiplin menabung di tabungan SimPel?',
    guideQuestions: [
      'Berapa target nominal yang ingin kamu kumpulkan?',
      'Strategi apa yang kamu lakukan agar bisa konsisten menabung setiap minggu?',
    ],
    rubric: 'Menyusun target finansial sederhana dan rencana aksi menabung.',
    status: 'published',
  },
];

export const seedReferences: Reference[] = [
  {
    id: 'REF-01',
    code: 'REF-01',
    title: 'Undang-Undang Republik Indonesia Nomor 7 Tahun 2011 tentang Mata Uang',
    sourceName: 'Lembaran Negara Republik Indonesia',
    publicationYear: '2011',
    url: 'https://www.bi.go.id',
    type: 'regulation',
    status: 'published',
  },
  {
    id: 'REF-02',
    code: 'REF-02',
    title: 'Panduan Edukasi Cinta, Bangga, Paham Rupiah untuk Sekolah Dasar',
    sourceName: 'Departemen Pengelolaan Uang Bank Indonesia',
    publicationYear: '2022',
    url: 'https://www.bi.go.id/id/rupiah/edukasi',
    type: 'guideline',
    status: 'published',
  },
  {
    id: 'REF-03',
    code: 'REF-03',
    title: 'Buku Seri Literasi Keuangan Siswa SD: Mengenal Rupiah dan Perbankan',
    sourceName: 'Otoritas Jasa Keuangan (OJK)',
    publicationYear: '2023',
    url: 'https://sikapiuangmu.ojk.go.id',
    type: 'book',
    status: 'published',
  },
  {
    id: 'REF-04',
    code: 'REF-04',
    title: 'Karakteristik Unsur Pengaman Uang Rupiah Kertas Tahun Emisi 2022',
    sourceName: 'Bank Indonesia',
    publicationYear: '2022',
    type: 'guideline',
    status: 'published',
  },
  {
    id: 'REF-05',
    code: 'REF-05',
    title: 'Sejarah Oeang Republik Indonesia: Tonggak Kedaulatan Finansial Bangsa',
    sourceName: 'Museum Bank Indonesia',
    publicationYear: '2021',
    type: 'article',
    status: 'published',
  },
  {
    id: 'REF-06',
    code: 'REF-06',
    title: 'Standar Nasional Pembayaran Digital QRIS bagi Usaha Mikro dan Konsumen',
    sourceName: 'Bank Indonesia & ASPI',
    publicationYear: '2023',
    type: 'regulation',
    status: 'published',
  },
];

export const seedTournamentPackages: TournamentPackage[] = [
  {
    id: 'PKG-01',
    code: 'PKG-01',
    title: 'Cerdas Rupiah Championship - SD Kelas 4',
    gradeLevel: 'SD Kelas 4',
    targetDurationMinutes: 15,
    totalQuestions: 20,
    passingScore: 70,
    status: 'published',
  },
  {
    id: 'PKG-02',
    code: 'PKG-02',
    title: 'Cerdas Rupiah Championship - SD Kelas 5',
    gradeLevel: 'SD Kelas 5',
    targetDurationMinutes: 15,
    totalQuestions: 20,
    passingScore: 75,
    status: 'published',
  },
  {
    id: 'PKG-03',
    code: 'PKG-03',
    title: 'Cerdas Rupiah Championship - SD Kelas 6',
    gradeLevel: 'SD Kelas 6',
    targetDurationMinutes: 15,
    totalQuestions: 20,
    passingScore: 80,
    status: 'published',
  },
];

// 60 Tournament Questions linking to sourcePracticeQuestionId
function generateTournamentQuestions(): TournamentQuestion[] {
  const list: TournamentQuestion[] = [];
  const practiceMap = seedPracticeQuestions;

  let tqCounter = 1;

  for (let pkgIdx = 0; pkgIdx < 3; pkgIdx++) {
    const pkg = seedTournamentPackages[pkgIdx];
    // Each package gets 20 questions
    for (let q = 0; q < 20; q++) {
      // Pick a practice question from the 110 pool
      const sourceIndex = (pkgIdx * 20 + q) % practiceMap.length;
      const srcQuestion = practiceMap[sourceIndex];
      const code = `TQ-${String(tqCounter).padStart(3, '0')}`;
      const id = code;

      list.push({
        id,
        packageId: pkg.id,
        sourcePracticeQuestionId: srcQuestion.id,
        code,
        question: srcQuestion.question,
        options: srcQuestion.options,
        correctAnswerIndex: srcQuestion.correctAnswerIndex,
        explanation: srcQuestion.explanation,
        points: 100,
        status: 'published',
      });
      tqCounter++;
    }
  }

  return list;
}

export const seedTournamentQuestions: TournamentQuestion[] = generateTournamentQuestions();

export const seedUsers: User[] = [
  // Super Admin Utama Tunggal Sistem
  {
    id: 'USR-SA-KEPSEK',
    name: 'Super Administrator',
    username: 'kepsek',
    email: 'kepsek@duniarupiah.id',
    password: 'dwija',
    role: 'superadmin',
    points: 0,
    level: 1,
    levelTitle: 'Super Administrator Sistem',
    currentXp: 0,
    maxXp: 100,
    avatar: 'superadmin',
    streakDays: 1,
    createdAt: '2026-08-01T00:00:00Z',
    isActive: true,
    school: 'Bank Indonesia',
  },
];

export const seedSchools: School[] = [];

export const seedClasses: Class[] = [];

export const seedClassMembers: ClassMember[] = [];

export const seedStudentProgress: StudentProgress[] = [];

export const seedTournamentEvents: TournamentEvent[] = [];

export const seedTournamentParticipants: TournamentParticipant[] = [];

export const seedTournamentResults: TournamentResult[] = [];

export const seedAuditLogs: ImportAuditLog[] = [
  {
    id: 'AUD-INIT',
    timestamp: '2026-08-15T08:00:00.000Z',
    importedBy: 'Admin Kurikulum Bank Indonesia',
    fileName: 'Content_Master_Jelajah_Rupiah_Canonical_v1.xlsx',
    totalRows: 242,
    createdCount: 242,
    updatedCount: 0,
    skippedCount: 0,
    errorCount: 0,
    details: {
      missionsCount: 9,
      lessonsCount: 24,
      activitiesCount: 18,
      questionsCount: 110,
      badgesCount: 9,
      reflectionsCount: 9,
      referencesCount: 6,
      packagesCount: 3,
      tournamentQuestionsCount: 60,
      eventsCount: 4,
    },
    statusSummary: 'success',
  },
];

export const seedWorkflowLogs: WorkflowReviewLog[] = [
  {
    id: 'WFL-001',
    entityType: 'mission',
    entityId: 'JR-C01',
    entityTitle: 'Kenalan dengan Rupiah (Metode 3D)',
    previousStatus: 'review',
    newStatus: 'published',
    reviewerId: 'USR-REV-001',
    reviewerName: 'Dr. Hendra Gunawan (Reviewer Ahli BI)',
    notes: 'Materi dan indikator 3D sudah selaras dengan standar edukasi Bank Indonesia. Disetujui untuk publikasi.',
    timestamp: '2026-08-10T14:30:00Z',
  },
  {
    id: 'WFL-002',
    entityType: 'lesson',
    entityId: 'MAT-001',
    entityTitle: 'Mengenal Uang Kertas & Logam',
    previousStatus: 'draft',
    newStatus: 'published',
    reviewerId: 'USR-REV-001',
    reviewerName: 'Dr. Hendra Gunawan (Reviewer Ahli BI)',
    notes: 'Kesesuaian gambar TE 2022 dan teks penjelasan anak SD sudah terverifikasi.',
    timestamp: '2026-08-10T14:35:00Z',
  },
  {
    id: 'WFL-003',
    entityType: 'question',
    entityId: 'QST-001',
    entityTitle: 'Soal Pengenalan Warna Rp100.000',
    previousStatus: 'review',
    newStatus: 'published',
    reviewerId: 'USR-REV-001',
    reviewerName: 'Dr. Hendra Gunawan (Reviewer Ahli BI)',
    notes: 'Opsi jawaban dan kunci A valid sesuai uang tahun emisi 2022.',
    timestamp: '2026-08-10T14:40:00Z',
  },
  {
    id: 'WFL-004',
    entityType: 'tournament_question',
    entityId: 'TQ-001',
    entityTitle: 'Varian Turnamen: Identifikasi Pecahan Merah',
    previousStatus: 'review',
    newStatus: 'published',
    reviewerId: 'USR-REV-001',
    reviewerName: 'Dr. Hendra Gunawan (Reviewer Ahli BI)',
    notes: 'Tingkat kesulitan kognitif C2 terstandar sesuai soal latihan QST-001.',
    timestamp: '2026-08-11T10:00:00Z',
  },
];

export const seedVersionHistory: ContentVersionEntry[] = [
  {
    id: 'VER-001',
    entityType: 'mission',
    entityId: 'JR-C01',
    versionNumber: 'v1.1',
    updatedBy: 'Admin Kurikulum BI',
    timestamp: '2026-08-10T12:00:00Z',
    changeSummary: 'Penyempurnaan deskripsi big question dan penambahan learning point.',
    snapshot: { title: 'Kenalan dengan Rupiah', questionDisplayCount: 5 },
  },
  {
    id: 'VER-002',
    entityType: 'lesson',
    entityId: 'MAT-001',
    versionNumber: 'v1.1',
    updatedBy: 'Admin Kurikulum BI',
    timestamp: '2026-08-10T12:15:00Z',
    changeSummary: 'Pembaruan caption gambar dan ringkasan interaktif 3D.',
    snapshot: { title: 'Mengenal Uang Kertas & Logam', readTimeMinutes: 3 },
  },
];
